import assert from "node:assert/strict";
import test from "node:test";

import { buildEstimatePdfAttachment, buildEstimatePdfFilename } from "./estimate-pdf.js";

const estimate = {
  title: "Martinez Driveway Proposal",
  scopeSummary: "Replace cracked driveway panels and restore broom-finish apron.",
  internalNotes: "Office-only pricing assumptions stay inside estimates.",
  customerNotes: "Two-day window once approved.",
  customer: { name: "Martinez Residence" },
  lead: { customer: "Martinez Residence", project: "Driveway replacement estimate" },
  items: [
    { description: "Concrete placement", quantity: 10, unit: "yd", unitPrice: 185 },
    { description: "Prep and cleanup", quantity: 1, unit: "lot", unitPrice: 650 },
  ],
  taxRate: 8.5,
  feesTotal: 125,
};

test("estimate PDF attachment uses a safe customer and project filename", () => {
  assert.equal(
    buildEstimatePdfFilename({
      ...estimate,
      customer: { name: "Martinez / Residence LLC" },
      lead: { customer: "Martinez / Residence LLC", project: "Driveway replacement: phase #1" },
    }),
    "Estimate-Martinez-Residence-LLC-Driveway-replacement-phase-1.pdf",
  );
});

test("estimate PDF attachment includes customer-facing proposal details only", () => {
  const attachment = buildEstimatePdfAttachment({
    companyName: "Concrete Ops Demo Company",
    companyProfile: {
      logoInitials: "CO",
      businessPhone: "(503) 555-0100",
      businessEmail: "office@concreteopsdemo.com",
      website: "https://concreteopsdemo.com",
      businessAddress: "1840 River Rd S, Salem, OR 97302",
      serviceArea: "Willamette Valley",
      licenseText: "CCB #123456 - Bonded and insured.",
    },
    printPacketFooter: "Generated by Concrete Ops for estimate review.",
    printPacketDisclaimer: "Review before sharing outside the company.",
    estimate,
  });
  const pdfText = attachment.content.toString("latin1");

  assert.equal(attachment.filename, "Estimate-Martinez-Residence-Driveway-replacement-estimate.pdf");
  assert.equal(attachment.contentType, "application/pdf");
  assert.match(pdfText, /%PDF-1\.4/);
  assert.match(pdfText, /Concrete Ops Demo Company/);
  assert.match(pdfText, /CO Concrete Ops Demo Company/);
  assert.match(pdfText, /503/);
  assert.match(pdfText, /office@concreteopsdemo\.com/);
  assert.match(pdfText, /1840 River Rd S, Salem, OR 97302/);
  assert.match(pdfText, /CCB #123456 - Bonded and insured\./);
  assert.match(pdfText, /Martinez Driveway Proposal/);
  assert.match(pdfText, /Martinez Residence/);
  assert.match(pdfText, /Driveway replacement estimate/);
  assert.match(pdfText, /Replace cracked driveway panels/);
  assert.match(pdfText, /Concrete placement/);
  assert.match(pdfText, /Qty: 10 yd/);
  assert.match(pdfText, /Unit price: \$185\.00/);
  assert.match(pdfText, /Subtotal: \$2,500\.00/);
  assert.match(pdfText, /Tax .*8\.5%.* \$212\.50/);
  assert.match(pdfText, /Fees: \$125\.00/);
  assert.match(pdfText, /Grand total: \$2,837\.50/);
  assert.match(pdfText, /Two-day window once approved\./);
  assert.match(pdfText, /Generated by Concrete Ops for estimate review\./);
  assert.match(pdfText, /Review before sharing outside the company\./);
  assert.doesNotMatch(pdfText, /Office-only pricing assumptions/);
});
