import assert from "node:assert/strict";
import test from "node:test";

import { buildEstimatePdfAttachment, buildEstimatePdfFilename } from "./estimate-pdf.js";

const estimate = {
  title: "Martinez Driveway Proposal",
  scopeSummary: "Replace cracked driveway panels and restore broom-finish apron.",
  internalNotes: "Office-only pricing assumptions stay inside estimates.",
  customerNotes: "Two-day window once approved.",
  customer: { name: "Martinez Residence" },
  lead: { customer: "Martinez Residence", project: "Driveway replacement estimate" },
  items: [
    { description: "Concrete placement", quantity: 10, unit: "yd", unitPrice: 185 },
    { description: "Prep and cleanup", quantity: 1, unit: "lot", unitPrice: 650 },
  ],
  taxRate: 8.5,
  feesTotal: 125,
};

function extractPdfText(buffer) {
  return Array.from(buffer.toString("latin1").matchAll(/<([0-9A-Fa-f]+)>/g))
    .map((match) => Buffer.from(match[1], "hex").toString("latin1"))
    .join("")
    .replace(/\s+/g, " ");
}

test("estimate PDF attachment uses a safe customer and project filename", () => {
  assert.equal(
    buildEstimatePdfFilename({
      ...estimate,
      customer: { name: "Martinez / Residence LLC" },
      lead: { customer: "Martinez / Residence LLC", project: "Driveway replacement: phase #1" },
    }),
    "Estimate-Martinez-Residence-LLC-Driveway-replacement-phase-1.pdf",
  );
});

test("estimate PDF attachment includes customer-facing proposal details only", async () => {
  const attachment = await buildEstimatePdfAttachment({
    companyName: "Concrete Ops Demo Company",
    companyProfile: {
      logoInitials: "CO",
      businessPhone: "(503) 555-0100",
      businessEmail: "office@concreteopsdemo.com",
      website: "https://concreteopsdemo.com",
      businessAddress: "1840 River Rd S, Salem, OR 97302",
      serviceArea: "Willamette Valley",
      licenseText: "CCB #123456 - Bonded and insured.",
    },
    printPacketFooter: "Generated by Concrete Ops for estimate review.",
    printPacketDisclaimer: "Review before sharing outside the company.",
    estimate,
  });
  const pdfText = attachment.content.toString("latin1");
  const decodedText = extractPdfText(attachment.content);

  assert.equal(attachment.filename, "Estimate-Martinez-Residence-Driveway-replacement-estimate.pdf");
  assert.equal(attachment.contentType, "application/pdf");
  assert.match(pdfText, /%PDF-1\.3/);
  assert.match(decodedText, /Concrete Ops Demo Company/);
  assert.match(decodedText, /CO/);
  assert.match(decodedText, /503/);
  assert.match(decodedText, /office@concreteopsdemo\.com/);
  assert.match(decodedText, /1840 River Rd S, Salem, OR 97302/);
  assert.match(decodedText, /CCB #123456 - Bonded and insured\./);
  assert.match(decodedText, /Estimate \/ Proposal/);
  assert.match(decodedText, /Martinez Driveway Proposal/);
  assert.match(decodedText, /Martinez Residence/);
  assert.match(decodedText, /Driveway replacement estimate/);
  assert.match(decodedText, /GRAND TOTAL/);
  assert.match(decodedText, /\$2,837\.50/);
  assert.match(decodedText, /SCOPE SUMMARY/);
  assert.match(decodedText, /Replace cracked driveway panels/);
  assert.match(decodedText, /Description/);
  assert.match(decodedText, /Qty/);
  assert.match(decodedText, /Unit Price/);
  assert.match(decodedText, /Line Total/);
  assert.match(decodedText, /Concrete placement/);
  assert.match(decodedText, /10/);
  assert.match(decodedText, /\$185\.00/);
  assert.match(decodedText, /Subtotal/);
  assert.match(decodedText, /\$2,500\.00/);
  assert.match(decodedText, /Tax \(8\.5%\)/);
  assert.match(decodedText, /\$212\.50/);
  assert.match(decodedText, /Fees/);
  assert.match(decodedText, /\$125\.00/);
  assert.match(decodedText, /CUSTOMER NOTES \/ TERMS/);
  assert.match(decodedText, /Two-day window once approved\./);
  assert.match(decodedText, /ACCEPTANCE/);
  assert.match(decodedText, /ACCEPTED BY/);
  assert.match(decodedText, /SIGNATURE/);
  assert.match(decodedText, /Generated by Concrete Ops for estimate review\./);
  assert.match(decodedText, /Review before sharing outside the company\./);
  assert.doesNotMatch(decodedText, /Office-only pricing assumptions/);
});
