export const DEMO_COMPANY_NAME = "Apex HQ Demo Company";

export const DEMO_CREDENTIALS = {
  email: "demo.ops@apexhq.app",
  password: "apexdemo123",
  name: "Demo Operator",
  role: "Operations Manager",
};

export const DEMO_USERS = [
  {
    id: "DEMO-U-ADMIN",
    email: "demo.admin@apexhq.app",
    password: "apexdemo123",
    name: "Demo Admin",
    role: "Administrator",
    phone: "503-555-0100",
  },
  {
    id: "DEMO-U-FOREMAN",
    email: "demo.foreman@apexhq.app",
    password: "apexdemo123",
    name: "Demo Foreman",
    role: "Foreman",
    phone: "503-555-0101",
  },
  {
    id: "DEMO-U-EMPLOYEE",
    email: "demo.employee@apexhq.app",
    password: "apexdemo123",
    name: "Demo Employee",
    role: "Employee",
    phone: "503-555-0102",
  },
];

export const DEMO_USER_EMAILS = DEMO_USERS.map((user) => user.email.toLowerCase());

export const INITIAL_CUSTOMERS = [
  {
    id: "C-1001",
    name: "Martinez Residence",
    company: "",
    phone: "503-555-0148",
    email: "martinez@example.test",
    city: "Salem",
    serviceArea: "Mid-Willamette Valley",
    status: "Active",
    notes: "Residential cedar fence customer. Prefers a text before the crew arrives.",
  },
  {
    id: "C-1002",
    name: "Salem Dental Office",
    company: "Salem Dental Office",
    phone: "503-555-0187",
    email: "office@salemdental.example.test",
    city: "Salem",
    serviceArea: "Salem",
    status: "Active",
    notes: "Commercial privacy screen and gate work with patient traffic to maintain during daytime hours.",
  },
  {
    id: "C-1003",
    name: "Valley View Apartments",
    company: "Valley View Apartments",
    phone: "541-555-0106",
    email: "maintenance@valleyview.example.test",
    city: "Keizer",
    serviceArea: "North Salem",
    status: "Active",
    notes: "Phased perimeter fence repair across occupied apartment buildings.",
  },
  {
    id: "C-1004",
    name: "Keizer Gate Project",
    company: "",
    phone: "503-555-0119",
    email: "keizer.patio@example.test",
    city: "Keizer",
    serviceArea: "Keizer",
    status: "Prospect",
    notes: "Gate repair prospect with latch, hinge, and access questions.",
  },
  {
    id: "C-1005",
    name: "Northwest Storage Yard",
    company: "Northwest Storage Yard",
    phone: "541-555-0162",
    email: "yard@nwstorage.example.test",
    city: "Albany",
    serviceArea: "Albany",
    status: "Active",
    notes: "Commercial yard security fence prospect with phased access scheduling.",
  },
];

export const INITIAL_LEADS = [
  {
    id: "L-1048",
    customerId: "C-1001",
    customer: "Martinez Residence",
    city: "Salem",
    project: "Cedar fence replacement estimate",
    status: "Approved",
    priority: "High",
    value: 12400,
    owner: "Demo Admin",
    source: "public_request_form",
    followUpDueAt: "2026-04-28",
    age: "1d",
    nextStep: "Finalize fence line, post layout, and install schedule",
    notes: "Submitted through the public estimate request flow, then approved for the backyard cedar fence replacement with two gates.",
  },
  {
    id: "L-1047",
    customerId: "C-1004",
    customer: "Keizer Gate Project",
    city: "Keizer",
    project: "Gate repair quote",
    status: "Site Visit",
    priority: "Normal",
    value: 8900,
    owner: "Demo Admin",
    source: "Referral",
    followUpDueAt: "2026-04-30",
    age: "2d",
    nextStep: "Confirm gate width, hinge side, latch style, and post condition",
    notes: "Customer wants the sagging gate rebuilt with a clean swing, matching cedar boards, and latch hardware options.",
  },
  {
    id: "L-1046",
    customerId: "C-1003",
    customer: "Valley View Apartments",
    city: "Keizer",
    project: "Perimeter fence section repair",
    status: "Estimate Sent",
    priority: "Normal",
    value: 6200,
    owner: "Demo Admin",
    source: "Call-in",
    followUpDueAt: "2026-04-29",
    age: "3d",
    nextStep: "Confirm phased fence section sequence with the maintenance team",
    notes: "Leaning fence sections were flagged near building C, the mailboxes, and the playground path.",
  },
  {
    id: "L-1045",
    customerId: "C-1002",
    customer: "Salem Dental Office",
    city: "Salem",
    project: "Clinic privacy screen install",
    status: "Approved",
    priority: "High",
    value: 18700,
    owner: "Demo Admin",
    source: "Existing Customer",
    followUpDueAt: "2026-04-26",
    age: "4d",
    nextStep: "Coordinate install window and patient access with the office manager",
    notes: "Patient access must stay open while the side-yard privacy screen and service gate are installed.",
  },
  {
    id: "L-1044",
    customerId: "C-1005",
    customer: "Northwest Storage Yard",
    city: "Albany",
    project: "Security fence estimate",
    status: "Contacted",
    priority: "Low",
    value: 23100,
    owner: "Demo Admin",
    source: "Referral",
    followUpDueAt: "2026-05-01",
    age: "5d",
    nextStep: "Review yard access, gate openings, and overnight security needs",
    notes: "Prospect is exploring phased fence installation so yard access can stay open during the work.",
  },
];

export const INITIAL_JOBS = [
  {
    id: "J-2201",
    customerId: "C-1001",
    leadId: "L-1048",
    title: "Martinez Cedar Fence Replacement",
    job: "Martinez Cedar Fence Replacement",
    customer: "Martinez Residence",
    address: "843 Creekside Ave NE, Salem, OR",
    siteContact: "Elena Martinez - 503-555-0148",
    scopeSummary: "Remove failing backyard fence sections, set new cedar posts, install rails and pickets, and hang two gates.",
    scheduledStart: "2026-04-25T07:30",
    scheduledEnd: "2026-04-26T16:30",
    estimatedDuration: "2 days",
    crewSizeNeeded: 3,
    equipmentNotes: "Post-hole auger, saws, level kit, nailer, and gate hardware on site.",
    safetyNotes: "Residential access control, saw PPE, utility locate review, and material staging spotter required.",
    materialNotes: "Cedar posts, rails, pickets, concrete post-set material, and gate hardware. No pricing shown.",
    fieldNotes: "Customer wants backyard access restored before evening school pickup.",
    assignedForemanId: "",
    assignedUserId: "",
    fieldPlanningVisible: true,
    visibleToForeman: true,
    status: "in_progress",
    stage: "In Progress",
    crew: "Demo crew",
    nextStep: "Finish gate alignment, clean up, and capture closeout photos",
    next: "Finish gate alignment, clean up, and capture closeout photos",
    due: "Today",
    progress: 72,
    notes: "Approved estimate converted into an active cedar fence replacement workflow.",
  },
  {
    id: "J-2198",
    customerId: "C-1002",
    leadId: "L-1045",
    title: "Salem Dental Privacy Screen",
    job: "Salem Dental Privacy Screen",
    customer: "Salem Dental Office",
    address: "1452 Orchard View Dr, Salem, OR",
    siteContact: "Tina Brooks - 503-555-0187",
    scopeSummary: "Install a side-yard privacy screen and service gate while keeping patient access open.",
    scheduledStart: "2026-04-24T07:00",
    scheduledEnd: "2026-04-25T15:30",
    estimatedDuration: "2 days",
    crewSizeNeeded: 2,
    equipmentNotes: "Post-hole tools, saws, level kit, narrow-access material staging, and gate hardware.",
    safetyNotes: "Patient walkway protection, service access signage, utility locate review, and saw dust control.",
    materialNotes: "Privacy screen boards, posts, rails, gate hardware, and trim notes only.",
    fieldNotes: "Office wants a before-and-after upload set for the demo walkthrough.",
    assignedForemanId: "",
    assignedUserId: "",
    fieldPlanningVisible: true,
    visibleToForeman: true,
    status: "in_progress",
    stage: "In Progress",
    crew: "Demo crew",
    nextStep: "Confirm final gate swing, trim cleanup, and patient access reopening",
    next: "Confirm final gate swing, trim cleanup, and patient access reopening",
    due: "Today",
    progress: 61,
    notes: "Commercial privacy screen workflow with reports, uploads, safety items, and material tickets.",
  },
  {
    id: "J-2192",
    customerId: "C-1003",
    leadId: "L-1046",
    title: "Valley View Fence Sections",
    job: "Valley View Fence Sections",
    customer: "Valley View Apartments",
    address: "2881 Valley View Loop N, Keizer, OR",
    siteContact: "Marco Diaz - 541-555-0106",
    scopeSummary: "Repair leaning fence sections in phases around occupied units.",
    scheduledStart: "2026-04-29T08:00",
    scheduledEnd: "2026-04-30T16:00",
    estimatedDuration: "2 days",
    crewSizeNeeded: 3,
    equipmentNotes: "Post puller, saws, string line, level kit, and compact material staging.",
    safetyNotes: "Resident foot traffic and playground path closure need morning walkthrough.",
    materialNotes: "Replacement posts, rails, pickets, fasteners, and gate latch notes. No pricing shown.",
    fieldNotes: "Useful for field planning and multi-section repair demo.",
    assignedForemanId: "",
    assignedUserId: "",
    fieldPlanningVisible: true,
    visibleToForeman: true,
    status: "planned",
    stage: "Planned",
    crew: "Plan only",
    nextStep: "Finalize section count and post layout",
    next: "Finalize section count and post layout",
    due: "Tue",
    progress: 15,
    notes: "Upcoming field-visible fence repair job for planning, takeoffs, and checklist demos.",
  },
  {
    id: "J-2204",
    customerId: "C-1004",
    leadId: "L-1047",
    title: "Keizer Gate Rebuild",
    job: "Keizer Gate Rebuild",
    customer: "Keizer Gate Project",
    address: "911 Birch Meadow Ct, Keizer, OR",
    siteContact: "C. Wallace - 503-555-0119",
    scopeSummary: "Rebuild a sagging backyard gate with matching cedar boards, new hinges, and latch hardware.",
    scheduledStart: "2026-05-02T07:30",
    scheduledEnd: "2026-05-03T16:00",
    estimatedDuration: "2 days",
    crewSizeNeeded: 4,
    equipmentNotes: "Saws, drill/driver, hinge jig, level kit, and post repair tools.",
    safetyNotes: "Backyard access through side gate and trip hazards near work area.",
    materialNotes: "Gate frame, cedar boards, hinges, latch, and fasteners only, no costs or pricing.",
    fieldNotes: "Good demo example for future scheduled work and field-safe planning.",
    assignedForemanId: "",
    assignedUserId: "",
    fieldPlanningVisible: false,
    visibleToForeman: false,
    status: "scheduled",
    stage: "Scheduled",
    crew: "Pending crew",
    nextStep: "Confirm gate hardware and access protection",
    next: "Confirm gate hardware and access protection",
    due: "Fri",
    progress: 10,
    notes: "Scheduled gate rebuild for proposal-to-production demo flow.",
  },
];

export const INITIAL_QUEUE_ITEMS = [
  { id: "Q-001", title: "Review Martinez fence closeout", meta: "Confirm finish photos, post-install items, and both material tickets are attached.", status: "Due today", done: false },
  { id: "Q-002", title: "Confirm Salem Dental access reopening", meta: "Make sure the privacy screen report and patient access notes are complete before the office walkthrough.", status: "Due today", done: false },
  { id: "Q-003", title: "Follow up Valley View fence phasing", meta: "Confirm section count, resident notices, and the next install window with maintenance.", status: "Tomorrow", done: false },
  { id: "Q-004", title: "Review open safety hazard", meta: "Open post-hole barricade needs a documented follow-up before residents return to the path.", status: "Needs review", done: false },
  { id: "Q-005", title: "Send gate hardware options", meta: "Customer is waiting on hinge, latch, and matching cedar board options.", status: "Ready", done: false },
];

export const INITIAL_ACTIVITY = [
  { id: "A-001", time: "3:18 PM", title: "Material ticket photo linked", detail: "Martinez fence material ticket photo was attached to the first delivery and is ready for the print packet." },
  { id: "A-002", time: "2:46 PM", title: "Safety concern reviewed", detail: "A near-miss material staging issue on the privacy screen job was reviewed with updated access guidance." },
  { id: "A-003", time: "1:45 PM", title: "Daily report submitted", detail: "Martinez fence report includes crew, weather, linear feet installed, gate notes, and safety observations." },
  { id: "A-004", time: "11:20 AM", title: "Photo evidence uploaded", detail: "Post layout, utility locate, material ticket, and finished gate photos were added to active jobs." },
  { id: "A-005", time: "9:34 AM", title: "Toolbox guidance acknowledged", detail: "The demo crew acknowledged the morning PPE check and material-staging safety reminder before work started." },
  { id: "A-006", time: "8:10 AM", title: "Install readiness checklist reviewed", detail: "Office reviewed the Martinez readiness checklist and cleared the fence install sequence." },
];
