export const DEMO_COMPANY_NAME = "Apex HQ Demo Company";

export const DEMO_CREDENTIALS = {
  email: "demo.ops@apexhq.app",
  password: "apexdemo123",
  name: "Jordan Berl",
  role: "Operations Manager",
};

export const DEMO_USERS = [
  {
    id: "DEMO-U-ADMIN",
    email: "demo.admin@apexhq.app",
    password: "apexdemo123",
    name: "Demo Admin",
    role: "Administrator",
    phone: "503-555-0100",
  },
  {
    id: "DEMO-U-FOREMAN",
    email: "demo.foreman@apexhq.app",
    password: "apexdemo123",
    name: "Demo Foreman",
    role: "Foreman",
    phone: "503-555-0101",
  },
  {
    id: "DEMO-U-EMPLOYEE",
    email: "demo.employee@apexhq.app",
    password: "apexdemo123",
    name: "Demo Employee",
    role: "Employee",
    phone: "503-555-0102",
  },
];

export const DEMO_USER_EMAILS = DEMO_USERS.map((user) => user.email.toLowerCase());

export const INITIAL_CUSTOMERS = [
  {
    id: "C-1001",
    name: "Martinez Residence",
    company: "",
    phone: "503-555-0148",
    email: "martinez@example.test",
    city: "Salem",
    serviceArea: "Mid-Willamette Valley",
    status: "Active",
    notes: "Residential driveway customer. Prefers a text before the crew arrives.",
  },
  {
    id: "C-1002",
    name: "Salem Dental Office",
    company: "Salem Dental Office",
    phone: "503-555-0187",
    email: "office@salemdental.example.test",
    city: "Salem",
    serviceArea: "Salem",
    status: "Active",
    notes: "ADA access work with patient traffic to maintain during daytime hours.",
  },
  {
    id: "C-1003",
    name: "Valley View Apartments",
    company: "Valley View Apartments",
    phone: "541-555-0106",
    email: "maintenance@valleyview.example.test",
    city: "Keizer",
    serviceArea: "North Salem",
    status: "Active",
    notes: "Multi-panel sidewalk replacement across occupied apartment buildings.",
  },
  {
    id: "C-1004",
    name: "Keizer Patio Project",
    company: "",
    phone: "503-555-0119",
    email: "keizer.patio@example.test",
    city: "Keizer",
    serviceArea: "Keizer",
    status: "Prospect",
    notes: "Stamped patio demo customer with color and border questions.",
  },
  {
    id: "C-1005",
    name: "Northwest Storage Yard",
    company: "Northwest Storage Yard",
    phone: "541-555-0162",
    email: "yard@nwstorage.example.test",
    city: "Albany",
    serviceArea: "Albany",
    status: "Active",
    notes: "Commercial yard slab prospect with phased pour scheduling.",
  },
];

export const INITIAL_LEADS = [
  {
    id: "L-1048",
    customerId: "C-1001",
    customer: "Martinez Residence",
    city: "Salem",
    project: "Driveway replacement estimate",
    status: "Approved",
    priority: "High",
    value: 12400,
    owner: "Demo Admin",
    source: "public_request_form",
    followUpDueAt: "2026-04-28",
    age: "1d",
    nextStep: "Finalize driveway sawcut and pour schedule",
    notes: "Submitted through the public estimate request flow, then approved for the driveway replacement with broom finish and widened apron.",
  },
  {
    id: "L-1047",
    customerId: "C-1004",
    customer: "Keizer Patio Project",
    city: "Keizer",
    project: "Stamped patio quote",
    status: "Site Visit",
    priority: "Normal",
    value: 8900,
    owner: "Demo Admin",
    source: "Referral",
    followUpDueAt: "2026-04-30",
    age: "2d",
    nextStep: "Confirm stamp pattern, drain layout, and color release sample",
    notes: "Customer wants a charcoal border, a clean slider transition, and care notes for the stamped finish.",
  },
  {
    id: "L-1046",
    customerId: "C-1003",
    customer: "Valley View Apartments",
    city: "Keizer",
    project: "Sidewalk panel replacement",
    status: "Estimate Sent",
    priority: "Normal",
    value: 6200,
    owner: "Demo Admin",
    source: "Call-in",
    followUpDueAt: "2026-04-29",
    age: "3d",
    nextStep: "Confirm phased panel sequence with the maintenance team",
    notes: "Trip-hazard panels were flagged near building C, the mailboxes, and the playground path.",
  },
  {
    id: "L-1045",
    customerId: "C-1002",
    customer: "Salem Dental Office",
    city: "Salem",
    project: "ADA ramp pour",
    status: "Approved",
    priority: "High",
    value: 18700,
    owner: "Demo Admin",
    source: "Existing Customer",
    followUpDueAt: "2026-04-26",
    age: "4d",
    nextStep: "Coordinate the pour window with the office manager",
    notes: "Patient access must stay open, and the office wants clean before-and-after documentation.",
  },
  {
    id: "L-1044",
    customerId: "C-1005",
    customer: "Northwest Storage Yard",
    city: "Albany",
    project: "Shop slab estimate",
    status: "Contacted",
    priority: "Low",
    value: 23100,
    owner: "Demo Admin",
    source: "Referral",
    followUpDueAt: "2026-05-01",
    age: "5d",
    nextStep: "Review yard access, truck routing, and drain locations",
    notes: "Prospect is exploring phased pours so yard access can stay open during the work.",
  },
];

export const INITIAL_JOBS = [
  {
    id: "J-2201",
    customerId: "C-1001",
    leadId: "L-1048",
    title: "Martinez Driveway Replacement",
    job: "Martinez Driveway Replacement",
    customer: "Martinez Residence",
    address: "843 Creekside Ave NE, Salem, OR",
    siteContact: "Elena Martinez - 503-555-0148",
    scopeSummary: "Remove and replace the front driveway, widen the apron, and broom finish the main panel.",
    scheduledStart: "2026-04-25T07:30",
    scheduledEnd: "2026-04-26T16:30",
    estimatedDuration: "2 days",
    crewSizeNeeded: 3,
    equipmentNotes: "Mini skid, plate compactor, saw, and bull float on site.",
    safetyNotes: "Residential traffic control, saw PPE, and delivery truck backing spotter required.",
    materialNotes: "4,000 PSI driveway mix, aggregate base, and fiber mesh. No pricing shown.",
    fieldNotes: "Customer wants finished access restored before evening school pickup.",
    assignedForemanId: "",
    assignedUserId: "",
    fieldPlanningVisible: true,
    visibleToForeman: true,
    status: "in_progress",
    stage: "In Progress",
    crew: "Demo crew",
    nextStep: "Finish pour, cure, and capture closeout photos",
    next: "Finish pour, cure, and capture closeout photos",
    due: "Today",
    progress: 72,
    notes: "Approved estimate converted into an active driveway replacement workflow.",
  },
  {
    id: "J-2198",
    customerId: "C-1002",
    leadId: "L-1045",
    title: "Salem Dental ADA Ramp",
    job: "Salem Dental ADA Ramp",
    customer: "Salem Dental Office",
    address: "1452 Orchard View Dr, Salem, OR",
    siteContact: "Tina Brooks - 503-555-0187",
    scopeSummary: "Demo and replace the front ADA ramp and landing while keeping patient access open.",
    scheduledStart: "2026-04-24T07:00",
    scheduledEnd: "2026-04-25T15:30",
    estimatedDuration: "2 days",
    crewSizeNeeded: 2,
    equipmentNotes: "Saw cutting, compacting, and narrow-access wheelbarrow placement.",
    safetyNotes: "Patient walkway protection, ADA detour signage, and saw-cut dust control.",
    materialNotes: "Ramp forms, detectable warning strip prep, and non-slip finish notes only.",
    fieldNotes: "Office wants a before-and-after upload set for the demo walkthrough.",
    assignedForemanId: "",
    assignedUserId: "",
    fieldPlanningVisible: true,
    visibleToForeman: true,
    status: "in_progress",
    stage: "In Progress",
    crew: "Demo crew",
    nextStep: "Confirm final discharge timing, edge finish, and patient access reopening",
    next: "Confirm final discharge timing, edge finish, and patient access reopening",
    due: "Today",
    progress: 61,
    notes: "Commercial ADA ramp workflow with reports, uploads, safety items, and delivery tickets.",
  },
  {
    id: "J-2192",
    customerId: "C-1003",
    leadId: "L-1046",
    title: "Valley View Sidewalk Panels",
    job: "Valley View Sidewalk Panels",
    customer: "Valley View Apartments",
    address: "2881 Valley View Loop N, Keizer, OR",
    siteContact: "Marco Diaz - 541-555-0106",
    scopeSummary: "Replace several trip-hazard sidewalk panels in phases around occupied units.",
    scheduledStart: "2026-04-29T08:00",
    scheduledEnd: "2026-04-30T16:00",
    estimatedDuration: "2 days",
    crewSizeNeeded: 3,
    equipmentNotes: "Saw, compact plate, wheelbarrow, and string line layout.",
    safetyNotes: "Resident foot traffic and playground path closure need morning walkthrough.",
    materialNotes: "Panel replacement mix, base rock, and cure blankets. No pricing shown.",
    fieldNotes: "Useful for field planning and multi-section calculator demo.",
    assignedForemanId: "",
    assignedUserId: "",
    fieldPlanningVisible: true,
    visibleToForeman: true,
    status: "planned",
    stage: "Planned",
    crew: "Plan only",
    nextStep: "Finalize panel count and sawcut layout",
    next: "Finalize panel count and sawcut layout",
    due: "Tue",
    progress: 15,
    notes: "Upcoming field-visible sidewalk repair job for planning, takeoffs, and checklist demos.",
  },
  {
    id: "J-2204",
    customerId: "C-1004",
    leadId: "L-1047",
    title: "Keizer Stamped Patio",
    job: "Keizer Stamped Patio",
    customer: "Keizer Patio Project",
    address: "911 Birch Meadow Ct, Keizer, OR",
    siteContact: "C. Wallace - 503-555-0119",
    scopeSummary: "Stamped backyard patio with charcoal border and broom-safe transition path.",
    scheduledStart: "2026-05-02T07:30",
    scheduledEnd: "2026-05-03T16:00",
    estimatedDuration: "2 days",
    crewSizeNeeded: 4,
    equipmentNotes: "Compactor, stamps, color hardener, and release prep.",
    safetyNotes: "Backyard access through side gate and hose trip hazards near patio exit.",
    materialNotes: "Stamped patio material notes only, no costs or pricing.",
    fieldNotes: "Good demo example for future scheduled work and field-safe planning.",
    assignedForemanId: "",
    assignedUserId: "",
    fieldPlanningVisible: false,
    visibleToForeman: false,
    status: "scheduled",
    stage: "Scheduled",
    crew: "Pending crew",
    nextStep: "Confirm stamp pattern and access protection",
    next: "Confirm stamp pattern and access protection",
    due: "Fri",
    progress: 10,
    notes: "Scheduled stamped patio job for proposal-to-production demo flow.",
  },
];

export const INITIAL_QUEUE_ITEMS = [
  { id: "Q-001", title: "Review Martinez driveway closeout", meta: "Confirm finish photos, post-pour items, and both delivery tickets are attached.", status: "Due today", done: false },
  { id: "Q-002", title: "Confirm Salem Dental access reopening", meta: "Make sure the ramp report and patient access notes are complete before the office walkthrough.", status: "Due today", done: false },
  { id: "Q-003", title: "Follow up Valley View panel phasing", meta: "Confirm section count, resident notices, and the next pour window with maintenance.", status: "Tomorrow", done: false },
  { id: "Q-004", title: "Review open safety hazard", meta: "Wet slab edge barricade needs a documented follow-up before the next truck arrives.", status: "Needs review", done: false },
  { id: "Q-005", title: "Send stamped patio finish options", meta: "Customer is waiting on the charcoal border sample and care notes.", status: "Ready", done: false },
];

export const INITIAL_ACTIVITY = [
  { id: "A-001", time: "3:18 PM", title: "Delivery ticket photo linked", detail: "Martinez driveway ticket photo was attached to the first load and is ready for the print packet." },
  { id: "A-002", time: "2:46 PM", title: "Safety concern reviewed", detail: "A near-miss truck access issue on the ADA ramp job was reviewed with updated backing guidance." },
  { id: "A-003", time: "1:45 PM", title: "Daily report submitted", detail: "Martinez driveway report includes crew, weather, yards poured, finish notes, and safety observations." },
  { id: "A-004", time: "11:20 AM", title: "Photo evidence uploaded", detail: "Forms-set, rebar inspection, delivery ticket, and broom-finish photos were added to active jobs." },
  { id: "A-005", time: "9:34 AM", title: "Toolbox guidance acknowledged", detail: "The demo crew acknowledged the morning PPE check and truck-backing safety reminder before work started." },
  { id: "A-006", time: "8:10 AM", title: "Pre-pour checklist reviewed", detail: "Office reviewed the Martinez pre-pour checklist and cleared the driveway pour sequence." },
];
