export const DEMO_CREDENTIALS = {
  email: "ops@lastyard.test",
  password: "concrete123",
  name: "Jordan Berl",
  role: "Operations Manager",
};

export const INITIAL_CUSTOMERS = [
  {
    id: "C-1001",
    name: "Megan Carter",
    company: "",
    phone: "541-555-0148",
    email: "megan.carter@example.test",
    city: "Albany",
    serviceArea: "Mid-Valley",
    status: "Active",
    notes: "Prefers text updates before crew arrival.",
  },
  {
    id: "C-1002",
    name: "Rob Jenkins",
    company: "",
    phone: "503-555-0187",
    email: "rob.jenkins@example.test",
    city: "Salem",
    serviceArea: "Salem",
    status: "Active",
    notes: "Wants stamped finish samples with any proposal revision.",
  },
  {
    id: "C-1003",
    name: "Alicia Nguyen",
    company: "",
    phone: "541-555-0106",
    email: "alicia.nguyen@example.test",
    city: "Corvallis",
    serviceArea: "Benton County",
    status: "Prospect",
    notes: "Best reached after 3 PM.",
  },
  {
    id: "C-1004",
    name: "Harris Auto",
    company: "Harris Auto",
    phone: "541-555-0119",
    email: "facilities@harrisauto.example.test",
    city: "Lebanon",
    serviceArea: "East Valley",
    status: "Active",
    notes: "Commercial customer with trench drain and rebar requirements.",
  },
  {
    id: "C-1005",
    name: "C. Wallace",
    company: "",
    phone: "503-555-0162",
    email: "c.wallace@example.test",
    city: "Keizer",
    serviceArea: "North Salem",
    status: "Prospect",
    notes: "Tight side-yard access noted during intake.",
  },
];

export const INITIAL_LEADS = [
  {
    id: "L-1048",
    customerId: "C-1001",
    customer: "Megan Carter",
    city: "Albany",
    project: "Driveway replacement",
    status: "New",
    priority: "High",
    value: 12400,
    owner: "Jacob",
    source: "Website",
    followUpDueAt: "2026-04-25",
    age: "2h",
    nextStep: "Call for same-day site review",
    notes: "Requested broom finish and widened apron.",
  },
  {
    id: "L-1047",
    customerId: "C-1002",
    customer: "Rob Jenkins",
    city: "Salem",
    project: "Stamped patio",
    status: "Site Visit",
    priority: "Normal",
    value: 8900,
    owner: "Office",
    source: "Referral",
    followUpDueAt: "2026-04-28",
    age: "1d",
    nextStep: "Send texture upgrade pricing",
    notes: "Customer wants schedule before Memorial Day.",
  },
  {
    id: "L-1046",
    customerId: "C-1003",
    customer: "Alicia Nguyen",
    city: "Corvallis",
    project: "Walkway repair",
    status: "Estimate Sent",
    priority: "Normal",
    value: 4200,
    owner: "Jacob",
    source: "Call-in",
    followUpDueAt: "2026-04-29",
    age: "2d",
    nextStep: "Follow up Thursday afternoon",
    notes: "Crack repair with broom finish patch.",
  },
  {
    id: "L-1045",
    customerId: "C-1004",
    customer: "Harris Auto",
    city: "Lebanon",
    project: "Shop slab",
    status: "Approved",
    priority: "High",
    value: 18700,
    owner: "Ray",
    source: "Repeat Customer",
    followUpDueAt: "2026-04-26",
    age: "3d",
    nextStep: "Collect deposit and create job",
    notes: "Scope expanded to include rebar and trench drain.",
  },
  {
    id: "L-1044",
    customerId: "C-1005",
    customer: "C. Wallace",
    city: "Keizer",
    project: "Concrete removal",
    status: "Contacted",
    priority: "Low",
    value: 3100,
    owner: "Office",
    source: "Drive-by",
    followUpDueAt: "2026-04-30",
    age: "4d",
    nextStep: "Confirm dumpster access",
    notes: "Tight side-yard access noted on call.",
  },
];

export const INITIAL_JOBS = [
  {
    id: "J-2201",
    customerId: "C-1002",
    job: "North Salem Patio",
    customer: "Rob Jenkins",
    address: "1452 Orchard View Dr, Salem, OR",
    siteContact: "Rob Jenkins · 503-555-0187",
    scopeSummary: "Stamped patio prep, pour, and finish.",
    estimatedDuration: "2 days",
    crewSizeNeeded: 5,
    equipmentNotes: "Plate compactor and saw setup on site.",
    safetyNotes: "Watch stamped release timing and wet-edge traffic.",
    materialNotes: "Color hardener and stamped mats only, no pricing.",
    fieldNotes: "Finish crew needs upload before report closeout.",
    assignedForemanId: "",
    assignedUserId: "",
    fieldPlanningVisible: true,
    visibleToForeman: true,
    stage: "In Progress",
    crew: "Miguel + 4",
    next: "Pour finish photos",
    due: "Today",
    progress: 68,
    notes: "Finish crew needs upload before report closeout.",
  },
  {
    id: "J-2198",
    customerId: "C-1001",
    job: "Carter Driveway",
    customer: "Megan Carter",
    address: "843 Creekside Ave NE, Albany, OR",
    siteContact: "Megan Carter · 541-555-0148",
    scopeSummary: "Driveway replacement with exposed aggregate border.",
    estimatedDuration: "3 days",
    crewSizeNeeded: 4,
    equipmentNotes: "Mini skid steer and early wash setup.",
    safetyNotes: "Residential street traffic control on pour day.",
    materialNotes: "Aggregate border and finish notes only, no pricing.",
    fieldNotes: "Customer approved exposed aggregate border.",
    assignedForemanId: "",
    assignedUserId: "",
    fieldPlanningVisible: true,
    visibleToForeman: true,
    stage: "Scheduled",
    crew: "Juan + 3",
    next: "Confirm concrete order",
    due: "Mon",
    progress: 25,
    notes: "Customer approved exposed aggregate border.",
  },
  {
    id: "J-2192",
    customerId: "C-1004",
    job: "Lebanon Shop Pad",
    customer: "Harris Auto",
    address: "2881 Airport Rd, Lebanon, OR",
    siteContact: "Harris Auto Facilities · 541-555-0119",
    scopeSummary: "Commercial shop pad with trench drain prep.",
    estimatedDuration: "4 days",
    crewSizeNeeded: 3,
    equipmentNotes: "Laser screed and rebar support needed.",
    safetyNotes: "Commercial traffic and trench safety plan required.",
    materialNotes: "Rebar and trench drain materials listed without pricing.",
    fieldNotes: "Waiting on material confirmation before restart.",
    assignedForemanId: "",
    assignedUserId: "",
    fieldPlanningVisible: false,
    visibleToForeman: false,
    stage: "Waiting",
    crew: "Ray + 2",
    next: "Ticket upload",
    due: "Thu",
    progress: 42,
    notes: "Waiting on final material ticket for billing packet.",
  },
];

export const INITIAL_QUEUE_ITEMS = [
  { id: "Q-001", title: "Call Megan Carter", meta: "New driveway lead - Albany", status: "Due today", done: false },
  { id: "Q-002", title: "Review North Salem photos", meta: "Daily report cannot close without uploads", status: "Blocked", done: false },
  { id: "Q-003", title: "Send revised shop slab estimate", meta: "Harris Auto - approved scope change", status: "Ready", done: false },
  { id: "Q-004", title: "Schedule toolbox talk", meta: "PPE refresh for saw cutting work", status: "This week", done: false },
];

export const INITIAL_ACTIVITY = [
  { id: "A-001", time: "1:43 PM", title: "Time entry updated", detail: "Miguel crew added 5.5 hours to North Salem Patio." },
  { id: "A-002", time: "12:18 PM", title: "Daily report submitted", detail: "Pour notes and weather conditions saved." },
  { id: "A-003", time: "11:42 AM", title: "Photos uploaded", detail: "8 progress photos added to Carter Driveway." },
  { id: "A-004", time: "9:30 AM", title: "Estimate viewed", detail: "Harris Auto opened the revised proposal." },
];
