import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

test("Apex Control Room route is extracted and wired through App", () => {
  const appSource = fs.readFileSync(new URL("./App.jsx", import.meta.url), "utf8");
  const componentSource = fs.readFileSync(new URL("./apex-control-room-components.jsx", import.meta.url), "utf8");
  const utilSource = fs.readFileSync(new URL("./apex-control-room-utils.js", import.meta.url), "utf8");

  assert.match(appSource, /const ApexControlRoomPage = lazyRouteComponent\(\(\) => import\("\.\/apex-control-room-components"\), "ApexControlRoomPage"\);/);
  assert.match(appSource, /if \(active === "apexControlRoom"\) return <ApexControlRoomPage \{\.\.\.props\}\s*\/>;/);
  assert.match(appSource, /\{ id: "apexControlRoom", label: "Apex Control Room", icon: "spark" \}/);

  assert.match(componentSource, /export function ApexControlRoomPage\b/);
  assert.match(componentSource, /deriveApexControlRoomState/);
  assert.match(componentSource, /Apex Control Room/);
  assert.match(componentSource, /Operating Signals/);
  assert.match(componentSource, /Next Best Actions/);
  assert.match(componentSource, /Decision Memory/);
  assert.match(componentSource, /Operating Rules/);
  assert.match(componentSource, /Agent Work Queue/);
  assert.match(componentSource, /Agent Run Ledger/);
  assert.match(componentSource, /Agent Safety Locks/);
  assert.match(componentSource, /Locked Agent Tasks/);
  assert.match(componentSource, /Knowledge Vault/);
  assert.match(componentSource, /Vault Safety Gates/);
  assert.match(componentSource, /Vault Sources/);
  assert.match(componentSource, /Vault Intake Status/);
  assert.match(componentSource, /Durable Apex OS memory/);
  assert.match(componentSource, /Ask Apex/);
  assert.match(componentSource, /Ask Apex Actions/);
  assert.match(componentSource, /Ask Apex Evidence/);
  assert.match(componentSource, /Source-Backed Answer Rules/);
  assert.match(componentSource, /askApexOs/);
  assert.match(componentSource, /Apex answer/);
  assert.match(componentSource, /No execution/);
  assert.match(componentSource, /Voice Interface/);
  assert.match(componentSource, /Voice Safety Gates/);
  assert.match(componentSource, /Voice Modes/);
  assert.match(componentSource, /Voice Approval Boundary/);
  assert.match(componentSource, /VoiceTranscriptPanel/);
  assert.match(componentSource, /Use in Ask Apex/);
  assert.match(componentSource, /Manual transcript only/);
  assert.match(componentSource, /Speech locked/);
  assert.match(componentSource, /Approval Command Center/);
  assert.match(componentSource, /Approval Packet/);
  assert.match(componentSource, /Approval Controls/);
  assert.match(componentSource, /Approval Sources/);
  assert.match(componentSource, /Execute locked/);
  assert.match(componentSource, /Release Monitoring/);
  assert.match(componentSource, /Daily Briefing/);
  assert.match(componentSource, /Release Readiness Packet/);
  assert.match(componentSource, /Monitoring Locks/);
  assert.match(componentSource, /Business Command Center/);
  assert.match(componentSource, /Business Gates/);
  assert.match(componentSource, /Launch \/ Founder Demo/);
  assert.match(componentSource, /Business Briefing/);
  assert.match(componentSource, /QA \/ Security Hardening/);
  assert.match(componentSource, /Hardening Locks/);
  assert.match(componentSource, /Completion Audit/);
  assert.match(componentSource, /Security Proof Sources/);
  assert.match(componentSource, /What John decided/);
  assert.match(componentSource, /Launch Readiness/);
  assert.match(componentSource, /Release Desk/);
  assert.match(utilSource, /export function deriveApexControlRoomState\b/);
  assert.match(utilSource, /deriveAgentOsInternalTaskOptions/);
  assert.match(utilSource, /deriveLaunchReadinessEvidenceState/);
  assert.match(utilSource, /getReleaseSafetySections/);
  assert.match(utilSource, /APEX_OS_DECISION_MEMORY_SEED/);
  assert.match(utilSource, /APEX_OS_OPERATING_RULES/);
  assert.match(utilSource, /function buildAgentWorkQueue/);
  assert.match(utilSource, /runStatusTone/);
  assert.match(utilSource, /APEX_OS_KNOWLEDGE_VAULT_CATEGORIES/);
  assert.match(utilSource, /APEX_OS_KNOWLEDGE_VAULT_SAFETY_RULES/);
  assert.match(utilSource, /function buildKnowledgeVaultState/);
  assert.match(utilSource, /APEX_OS_CHAT_CONTEXTS/);
  assert.match(utilSource, /APEX_OS_CHAT_ACTION_LOCKS/);
  assert.match(utilSource, /function buildAskApexChatState/);
  assert.match(utilSource, /APEX_OS_VOICE_MODES/);
  assert.match(utilSource, /APEX_OS_VOICE_SAFETY_GATES/);
  assert.match(utilSource, /function buildVoiceInterfaceState/);
  assert.match(utilSource, /APEX_OS_APPROVAL_PACKET_FIELDS/);
  assert.match(utilSource, /APEX_OS_APPROVAL_CONTROL_LOCKS/);
  assert.match(utilSource, /function buildApprovalCommandCenterState/);
  assert.match(utilSource, /APEX_OS_RELEASE_MONITORING_CHECKS/);
  assert.match(utilSource, /APEX_OS_RELEASE_MONITORING_LOCKS/);
  assert.match(utilSource, /function buildReleaseMonitoringState/);
  assert.match(utilSource, /APEX_OS_BUSINESS_QUEUE_ROWS/);
  assert.match(utilSource, /APEX_OS_BUSINESS_GATES/);
  assert.match(utilSource, /function buildBusinessCommandCenterState/);
  assert.match(utilSource, /APEX_OS_QA_SECURITY_EVIDENCE_ROWS/);
  assert.match(utilSource, /APEX_OS_QA_SECURITY_LOCKS/);
  assert.match(utilSource, /function buildQaSecurityHardeningState/);
});
