import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

test("Apex Control Room route is extracted and wired through App", () => {
  const appSource = fs.readFileSync(new URL("./App.jsx", import.meta.url), "utf8");
  const componentSource = fs.readFileSync(new URL("./apex-control-room-components.jsx", import.meta.url), "utf8");
  const utilSource = fs.readFileSync(new URL("./apex-control-room-utils.js", import.meta.url), "utf8");
  const cssSource = fs.readFileSync(new URL("./index.css", import.meta.url), "utf8");

  assert.match(appSource, /const ApexControlRoomPage = lazyRouteComponent\(\(\) => import\("\.\/apex-control-room-components"\), "ApexControlRoomPage"\);/);
  assert.match(appSource, /if \(active === "apexControlRoom"\) return <ApexControlRoomPage \{\.\.\.props\}\s*\/>;/);
  assert.match(appSource, /\{ id: "apexControlRoom", label: "Apex Control Room", icon: "spark" \}/);

  assert.match(componentSource, /export function ApexControlRoomPage\b/);
  assert.match(componentSource, /deriveApexControlRoomState/);
  assert.match(componentSource, /Apex Control Room/);
  assert.match(componentSource, /APEX_CONTROL_ROOM_SECTIONS/);
  assert.match(componentSource, /aria-label="Apex Control Room sections"/);
  assert.match(componentSource, /ControlRoomCategoryShell/);
  assert.match(componentSource, /Category Map/);
  assert.match(componentSource, /ApexRoomLauncher/);
  assert.match(componentSource, /aria-label="Apex Control Room command room launcher"/);
  assert.match(componentSource, /Room switcher/);
  assert.match(componentSource, /The cockpit stays as Apex's home/);
  assert.match(componentSource, /ControlRoomRoomTabs/);
  assert.match(componentSource, /Overview room sections/);
  assert.match(componentSource, /Memory room sections/);
  assert.match(componentSource, /Agent room sections/);
  assert.match(componentSource, /Approval room sections/);
  assert.match(componentSource, /Release room sections/);
  assert.match(componentSource, /Business room sections/);
  assert.match(componentSource, /Trust room sections/);
  assert.match(componentSource, /KPI strip/);
  assert.match(componentSource, /Command board/);
  assert.match(componentSource, /Control plane/);
  assert.match(componentSource, /Release desk/);
  assert.match(componentSource, /Finished OS/);
  assert.match(componentSource, /sectionId="overview"/);
  assert.match(componentSource, /sectionId="memory"/);
  assert.match(componentSource, /sectionId="agents"/);
  assert.match(componentSource, /sectionId="approvals"/);
  assert.match(componentSource, /sectionId="release"/);
  assert.match(componentSource, /sectionId="business"/);
  assert.match(componentSource, /sectionId="trust"/);
  assert.match(componentSource, /sectionId="personal"/);
  assert.match(componentSource, /ApexCockpitScreen/);
  assert.match(componentSource, /ApexCockpitSidebar/);
  assert.match(componentSource, /ApexCockpitAvatar/);
  assert.match(componentSource, /APEX_COCKPIT_VOICE_STATES/);
  assert.match(componentSource, /data-voice-state/);
  assert.match(componentSource, /co-apex-life-body/);
  assert.match(componentSource, /co-apex-mini-waveform--/);
  assert.match(componentSource, /resolveApexCockpitAnswerText/);
  assert.match(componentSource, /speakCockpitAnswer/);
  assert.match(componentSource, /aria-label="Apex cockpit sections"/);
  assert.match(componentSource, /aria-label="Apex digital body"/);
  assert.match(componentSource, /Apex Boundaries/);
  assert.match(componentSource, /Apex is listening/);
  assert.match(componentSource, /Voice \+ answers/);
  assert.match(componentSource, /const \[activeSection, setActiveSection\] = useState\("apex"\);/);
  assert.match(componentSource, /Operating Signals/);
  assert.match(componentSource, /Phase 3 State Packet/);
  assert.match(componentSource, /Confidence:/);
  assert.match(componentSource, /Read-only/);
  assert.match(componentSource, /Next Best Actions/);
  assert.match(componentSource, /Decision Memory/);
  assert.match(componentSource, /Operating Rules/);
  assert.match(componentSource, /What Did I Decide\?/);
  assert.match(componentSource, /DecisionMemoryManager/);
  assert.match(componentSource, /createApexOsMemory/);
  assert.match(componentSource, /getApexOsMemory/);
  assert.match(componentSource, /updateApexOsMemory/);
  assert.match(componentSource, /Draft memory/);
  assert.match(componentSource, /Load decisions/);
  assert.match(componentSource, /No hidden memory/);
  assert.match(componentSource, /Agent Work Queue/);
  assert.match(componentSource, /Agent Run Ledger/);
  assert.match(componentSource, /Agent Safety Locks/);
  assert.match(componentSource, /Agent Control Plane/);
  assert.match(componentSource, /AgentControlPlanePanel/);
  assert.match(componentSource, /createApexOsAgentControlRequest/);
  assert.match(componentSource, /getApexOsAgentControl/);
  assert.match(componentSource, /updateApexOsAgentControlRequest/);
  assert.match(componentSource, /createApexOsAutonomyRun/);
  assert.match(componentSource, /getApexOsAutonomyRuns/);
  assert.match(componentSource, /updateApexOsAutonomyRun/);
  assert.match(componentSource, /draftApexOsAutonomyRunInternalWork/);
  assert.match(componentSource, /Request control/);
  assert.match(componentSource, /Load controls/);
  assert.match(componentSource, /Background loops locked/);
  assert.match(componentSource, /Agent Handoff Drafts/);
  assert.match(componentSource, /ExecutionHandoffDraftPanel/);
  assert.match(componentSource, /createApexOsExecutionHandoff/);
  assert.match(componentSource, /getApexOsExecutionHandoffs/);
  assert.match(componentSource, /updateApexOsExecutionHandoff/);
  assert.match(componentSource, /Queue locked/);
  assert.match(componentSource, /Run locked/);
  assert.match(componentSource, /Save updates/);
  assert.match(componentSource, /Validation results after work finishes/);
  assert.match(componentSource, /Result report after work finishes/);
  assert.match(componentSource, /Decision memory update to save as suggested memory/);
  assert.match(componentSource, /Locked Agent Tasks/);
  assert.match(componentSource, /Knowledge Vault/);
  assert.match(componentSource, /Knowledge Upload Vault/);
  assert.match(componentSource, /KnowledgeVaultManager/);
  assert.match(componentSource, /pdfjs-dist/);
  assert.match(componentSource, /pdf\.worker\.mjs/);
  assert.match(componentSource, /extractPdfKnowledgeText/);
  assert.match(componentSource, /Duplicate source guard/);
  assert.match(componentSource, /Draft knowledge/);
  assert.match(componentSource, /Load vault/);
  assert.match(componentSource, /Review required/);
  assert.match(componentSource, /Knowledge Intelligence/);
  assert.match(componentSource, /Refresh intelligence/);
  assert.match(componentSource, /Ranked Evidence/);
  assert.match(componentSource, /Conflict warnings/);
  assert.match(componentSource, /Confidence Labels/);
  assert.match(componentSource, /getApexOsKnowledgeIntelligence/);
  assert.match(componentSource, /buildApexOsKnowledgeIntelligence/);
  assert.match(componentSource, /application\/pdf/);
  assert.match(componentSource, /All categories/);
  assert.match(componentSource, /All sources/);
  assert.match(componentSource, /All review states/);
  assert.match(componentSource, /Last 30 days/);
  assert.match(componentSource, /Vault Safety Gates/);
  assert.match(componentSource, /Vault Sources/);
  assert.match(componentSource, /Vault Intake Status/);
  assert.match(componentSource, /Durable Apex OS memory/);
  assert.match(componentSource, /Ask Apex/);
  assert.match(componentSource, /Ask Apex anything/);
  assert.match(componentSource, /Apex Response/);
  assert.match(componentSource, /Voice Open/);
  assert.match(componentSource, /Transcript/);
  assert.match(componentSource, /Awareness/);
  assert.match(componentSource, /onClick=\{\(\) => onChange\("overview"\)\}>View Overview/);
  assert.match(componentSource, /onClick=\{\(\) => onChange\("approvals"\)\}>View Approvals/);
  assert.match(componentSource, /onClick=\{\(\) => onChange\("memory"\)\}>Review Memory/);
  assert.match(componentSource, /onClick=\{\(\) => onChange\("agents"\)\}>View Agents/);
  assert.match(componentSource, /onClick=\{\(\) => onChange\("release"\)\}>View Release/);
  assert.doesNotMatch(componentSource, /Jun 4, 9:15 AM/);
  assert.match(componentSource, /Ask Apex Draft Actions/);
  assert.match(componentSource, /Evidence used/);
  assert.match(componentSource, /Trusted Memories/);
  assert.match(componentSource, /askApexOs/);
  assert.match(componentSource, /Apex answer/);
  assert.match(componentSource, /Save as decision/);
  assert.match(componentSource, /Create task draft/);
  assert.match(componentSource, /Needs approval/);
  assert.match(componentSource, /buildApexOsAskDecisionDraft/);
  assert.match(componentSource, /buildApexOsAskExecutionHandoffDraft/);
  assert.match(componentSource, /buildApexOsAskApprovalPacketDraft/);
  assert.match(componentSource, /No execution/);
  assert.match(componentSource, /ApexMiniWaveform/);
  assert.match(componentSource, /Apex is standing by/);
  assert.match(componentSource, /Apex hears you/);
  assert.match(componentSource, /Command stream/);
  assert.match(componentSource, /buildApexCockpitCommandRoute/);
  assert.match(componentSource, /previousRoute/);
  assert.match(componentSource, /get this done/);
  assert.match(componentSource, /start-live-operator-run/);
  assert.match(componentSource, /Start private run/);
  assert.match(componentSource, /buildApexCockpitTurnMemory/);
  assert.match(componentSource, /Recent page conversation/);
  assert.match(componentSource, /buildApexCockpitLiveRunMemoryContext/);
  assert.match(componentSource, /Reviewed live-run memory/);
  assert.match(componentSource, /ApexCockpitCommandStream/);
  assert.match(componentSource, /Agent control/);
  assert.match(componentSource, /Release desk/);
  assert.match(componentSource, /Business ops/);
  assert.match(componentSource, /Personal operating layer/);
  assert.match(componentSource, /Trust and QA/);
  assert.match(componentSource, /APEX_COCKPIT_SILENCE_MS/);
  assert.match(componentSource, /startCockpitVoiceLevelMonitor/);
  assert.match(componentSource, /finishCockpitVoiceTurn/);
  assert.match(componentSource, /cockpitAutoListening/);
  assert.match(componentSource, /cockpitMicPermissionState/);
  assert.match(componentSource, /cockpitVoiceWakeAttempted/);
  assert.match(componentSource, /formatApexCockpitClock/);
  assert.match(componentSource, /cockpitFocusDrawer/);
  assert.match(componentSource, /cockpitImmersiveMode/);
  assert.match(componentSource, /cockpitSpotlightMode/);
  assert.match(componentSource, /cockpitConsoleTab/);
  assert.match(componentSource, /Apex focus controls/);
  assert.match(componentSource, /Apex focus drawer/);
  assert.match(componentSource, /co-apex-cockpit-screen--immersive/);
  assert.match(componentSource, /co-apex-cockpit-screen--spotlight/);
  assert.match(componentSource, /co-apex-cockpit-screen--full-console/);
  assert.match(componentSource, /Return to immersive Apex body/);
  assert.match(componentSource, /Return to Apex spotlight/);
  assert.match(componentSource, /Open full operator console dock/);
  assert.match(componentSource, /co-apex-cockpit-live-console--dock/);
  assert.match(componentSource, /Apex mobile operator dock/);
  assert.match(componentSource, /co-apex-cockpit-mobile-dock/);
  assert.match(componentSource, /co-apex-cockpit-mobile-dock-tab/);
  assert.match(componentSource, /co-apex-cockpit-content-shell/);
  assert.match(componentSource, /co-apex-cockpit-operator-stack/);
  assert.match(componentSource, /co-apex-cockpit-operator-metrics/);
  assert.match(componentSource, /co-apex-cockpit-console-tabs/);
  assert.match(componentSource, /Autonomy Core/);
  assert.match(componentSource, /Safe internal drafts are on/);
  assert.match(componentSource, /AutonomyRunCenterPanel/);
  assert.match(componentSource, /Autonomy Run Center/);
  assert.match(componentSource, /Plan \+ gates/);
  assert.match(componentSource, /Current command route/);
  assert.match(componentSource, /Next safe action/);
  assert.match(componentSource, /Save a run/);
  assert.match(componentSource, /Run ledger/);
  assert.match(componentSource, /Draft internal work/);
  assert.match(componentSource, /Saved runs/);
  assert.match(componentSource, /Draft locked run/);
  assert.match(componentSource, /Execution gates/);
  assert.match(componentSource, /externalActionsLocked/);
  assert.match(componentSource, /co-apex-cockpit-screen--focus/);
  assert.match(componentSource, /co-apex-cockpit-focus-bar/);
  assert.match(componentSource, /co-apex-cockpit-focus-center/);
  assert.match(componentSource, /cockpitConversationMode/);
  assert.match(componentSource, /cockpitBargeInEnabled/);
  assert.match(componentSource, /cockpitVoiceProfile/);
  assert.match(componentSource, /cockpitPersonalityMode/);
  assert.match(componentSource, /cockpitOutputLevel/);
  assert.match(componentSource, /APEX_COCKPIT_BARGE_IN_THRESHOLD/);
  assert.match(componentSource, /APEX_COCKPIT_BARGE_IN_GRACE_MS/);
  assert.match(componentSource, /APEX_COCKPIT_VOICE_PROFILES/);
  assert.match(componentSource, /APEX_COCKPIT_PERSONALITY_MODES/);
  assert.match(componentSource, /buildApexCockpitProactiveBriefing/);
  assert.match(componentSource, /resolveApexCockpitLatestTrustedRunMemory/);
  assert.match(componentSource, /Latest trusted run history/);
  assert.match(componentSource, /buildApexCockpitQuestionEnvelope/);
  assert.match(componentSource, /buildApexCockpitAgentControlDraft/);
  assert.match(componentSource, /createCockpitAgentRequestFromCommand/);
  assert.match(componentSource, /handleCockpitVoiceBargeIn/);
  assert.match(componentSource, /startCockpitOutputLevelMonitor/);
  assert.match(componentSource, /stopCockpitOutputLevelMonitor/);
  assert.match(componentSource, /buildApexCockpitNowState/);
  assert.match(componentSource, /Apex Now/);
  assert.match(componentSource, /Apex live operator state/);
  assert.match(componentSource, /Next Safe Move/);
  assert.match(componentSource, /Working private run/);
  assert.match(componentSource, /Apex operator console tabs/);
  assert.match(componentSource, /Operator Console/);
  assert.match(componentSource, /Console tab: \{tab\.label\}/);
  assert.match(componentSource, /Open \$\{tab\.label\} console lane/);
  assert.match(componentSource, /Apex operator loop lanes/);
  assert.match(componentSource, /Live Operator Mode/);
  assert.match(componentSource, /Trusted run history/);
  assert.match(componentSource, /trustedRunMemoryCount/);
  assert.match(componentSource, /run history/);
  assert.match(componentSource, /Live Run/);
  assert.match(componentSource, /Active Run Session/);
  assert.match(componentSource, /Report Done/);
  assert.match(componentSource, /Cycle/);
  assert.match(componentSource, /Auto Prep/);
  assert.match(componentSource, /Proof/);
  assert.match(componentSource, /updateCockpitActiveRunStatus/);
  assert.match(componentSource, /draftCockpitActiveRunInternalWork/);
  assert.match(componentSource, /continueCockpitActiveRunPrivately/);
  assert.match(componentSource, /proofCheckCockpitActiveRunPrivately/);
  assert.match(componentSource, /cycleCockpitActiveRunPrivately/);
  assert.match(componentSource, /advanceApexOsAutonomyRunPrivatePrep/);
  assert.match(componentSource, /validateApexOsAutonomyRunPrivateProof/);
  assert.match(componentSource, /runApexOsAutonomyRunPrivateOperatorCycle/);
  assert.match(componentSource, /buildApexOsAutonomyRunNextPrivateMove/);
  assert.match(componentSource, /cockpitNextPrivateMove/);
  assert.match(componentSource, /workCockpitActiveRunNextMove/);
  assert.match(componentSource, /Apex Work Loop/);
  assert.match(componentSource, /Apex private work loop/);
  assert.match(componentSource, /Apex mobile private work loop/);
  assert.match(componentSource, /Let Apex work the next private safe move/);
  assert.match(componentSource, /buildApexOsAutonomyRunHeartbeat/);
  assert.match(componentSource, /buildApexOsAutonomyRunHandback/);
  assert.match(componentSource, /buildApexCockpitRunHandbackText/);
  assert.match(componentSource, /deliverCockpitRunHandback/);
  assert.match(componentSource, /buildApexCockpitHeartbeatText/);
  assert.match(componentSource, /deliverCockpitSessionHeartbeat/);
  assert.match(componentSource, /function deliverCockpitSessionHeartbeat[\s\S]*setCockpitError\(""\);[\s\S]*Apex Live Session Heartbeat/);
  assert.match(componentSource, /Live Session Heartbeat/);
  assert.match(componentSource, /Speak Check-In/);
  assert.match(componentSource, /Apex Live Session Heartbeat/);
  assert.match(componentSource, /Apex operator handback/);
  assert.match(componentSource, /Operator Handback/);
  assert.match(componentSource, /Speak Handback/);
  assert.match(componentSource, /What I Did/);
  assert.match(componentSource, /Proof I Have/);
  assert.match(componentSource, /What I Need/);
  assert.match(componentSource, /Still Locked/);
  assert.match(componentSource, /function deliverCockpitRunHandback[\s\S]*setCockpitError\(""\);[\s\S]*Apex Operator Handback/);
  assert.match(componentSource, /buildApexOsAutonomyRunProactiveCheckIn/);
  assert.match(componentSource, /buildApexOsAutonomyRunProactiveMemoryDraft/);
  assert.match(componentSource, /buildApexCockpitProactiveCheckInText/);
  assert.match(componentSource, /deliverCockpitProactiveCheckIn/);
  assert.match(componentSource, /saveCockpitProactiveCheckInMemory/);
  assert.match(componentSource, /cockpitProactiveMemoryIds/);
  assert.match(componentSource, /cockpitProactiveMemoryNotice/);
  assert.match(componentSource, /cockpitLastProactiveSignatureRef/);
  assert.match(componentSource, /cockpitVisibleProactiveCheckIn/);
  assert.match(componentSource, /Proactive Check-In/);
  assert.match(componentSource, /Speak Latest/);
  assert.match(componentSource, /Draft Memory/);
  assert.match(componentSource, /Suggested proactive memory/);
  assert.match(componentSource, /manual approval is still required/);
  assert.match(componentSource, /Apex Proactive Check-In/);
  assert.match(componentSource, /function deliverCockpitProactiveCheckIn[\s\S]*setCockpitError\(""\);[\s\S]*Apex Proactive Check-In/);
  assert.match(componentSource, /cockpitVisibleOperatorPercent/);
  assert.match(componentSource, /summarizeApexCockpitRunProgress/);
  assert.match(componentSource, /Run reported complete/);
  assert.match(componentSource, /createCockpitLiveRunFromCommand/);
  assert.match(componentSource, /autoCycle/);
  assert.match(componentSource, /live-run-cycled/);
  assert.match(componentSource, /private run, prepared internal drafts, checked proof/);
  assert.match(componentSource, /Proactive Pulse/);
  assert.match(componentSource, /Operator judgment/);
  assert.match(componentSource, /Speak Judgment/);
  assert.match(componentSource, /buildApexCockpitOperatorJudgmentRows/);
  assert.match(componentSource, /buildApexCockpitOperatorJudgmentText/);
  assert.match(componentSource, /deliverCockpitOperatorJudgment/);
  assert.match(componentSource, /Execution, sends, billing, provider work, production changes, deletion, deploy, rollback, and irreversible actions stay locked/);
  assert.match(componentSource, /buildApexCockpitFollowUpPrompts/);
  assert.match(componentSource, /Continue Memory/);
  assert.match(componentSource, /Continue from trusted run memory/);
  assert.match(componentSource, /liveOperatorMemory,/);
  assert.match(componentSource, /loadCockpitFollowUpPrompt/);
  assert.match(componentSource, /Apex next turn prompts/);
  assert.match(componentSource, /Apex mobile next turn prompts/);
  assert.match(componentSource, /Press Ask or say it out loud; execution stays locked/);
  assert.match(componentSource, /Get this done as a private run/);
  assert.match(componentSource, /refreshCockpitLivePulse/);
  assert.match(componentSource, /Auto Check/);
  assert.match(componentSource, /Check Now/);
  assert.match(componentSource, /getApexOsBuildAwareness/);
  assert.match(componentSource, /getApexOsDailyBriefing/);
  assert.match(componentSource, /getApexOsAutonomyRuns/);
  assert.match(componentSource, /buildApexCockpitPulseRows/);
  assert.match(componentSource, /summarizeApexCockpitLivePulse/);
  assert.match(componentSource, /Apex Live Operator Mode/);
  assert.match(componentSource, /liveOperatorMode/);
  assert.match(componentSource, /Voice Identity/);
  assert.match(componentSource, /Barge-in On/);
  assert.match(componentSource, /Brief Me/);
  assert.match(componentSource, /Agent Draft/);
  assert.match(componentSource, /Draft locked request/);
  assert.match(componentSource, /Apex Life operator mode/);
  assert.match(componentSource, /Apex Life Voice\/Text Command/);
  assert.match(componentSource, /Execution remains locked/);
  assert.match(componentSource, /Pause Voice/);
  assert.match(componentSource, /Resume Voice/);
  assert.match(componentSource, /Wake Apex/);
  assert.match(componentSource, /Tap Wake Apex once/);
  assert.match(componentSource, /Voice is wake-gated, visible, and ready for a natural turn/);
  assert.match(componentSource, /Interrupt Voice/);
  assert.match(componentSource, /interruptCockpitVoicePlayback/);
  assert.match(componentSource, /recordCockpitInterruption/);
  assert.match(componentSource, /buildApexCockpitTurnMemoryDraft/);
  assert.match(componentSource, /buildApexCockpitRunMemoryDraft/);
  assert.match(componentSource, /buildApexCockpitLiveOperatorMemorySnapshot/);
  assert.match(componentSource, /findApexCockpitRunMemoryReviewRow/);
  assert.match(componentSource, /reviewCockpitRunMemory/);
  assert.match(componentSource, /redactApexOsMemoryText/);
  assert.match(componentSource, /summarizeApexOsLiveOperatorMemory/);
  assert.match(componentSource, /Apex answer summary/);
  assert.match(componentSource, /apex-live-operator-turn/);
  assert.match(componentSource, /apex-live-operator-run/);
  assert.match(componentSource, /rememberCockpitTurnFromAnswer/);
  assert.match(componentSource, /Suggested memory saved from this live turn/);
  assert.match(componentSource, /Suggested run memory/);
  assert.match(componentSource, /manual approval required before trusted memory/);
  assert.match(componentSource, /Apex Live Operator Mode answer; manual approval required before trusted memory/);
  assert.match(componentSource, /Run Memory Review/);
  assert.match(componentSource, /Apex run memory review/);
  assert.match(componentSource, /Apex mobile run memory review/);
  assert.match(componentSource, /Trust Memory/);
  assert.match(componentSource, /Archive/);
  assert.match(componentSource, /Trust reviewed Apex run memory/);
  assert.match(componentSource, /Trust reviewed Apex run memory from mobile/);
  assert.match(componentSource, /Memory stays suggested until you trust it/);
  assert.match(componentSource, /Run memory is trusted/);
  assert.match(componentSource, /Math\.max\(Number\(liveOperatorMode\.jarvisBehaviorPercent \|\| 0\), 92\)/);
  assert.match(componentSource, /Caption barge-in/);
  assert.match(componentSource, /Manual interruption/);
  assert.match(componentSource, /cockpitPendingInterruptionRef/);
  assert.match(componentSource, /Apex stopped speaking and kept listening/);
  assert.match(componentSource, /The operator interrupted Apex while it was speaking/);
  assert.match(componentSource, /interruption-reading/);
  assert.match(componentSource, /Voice is open\. I'm listening while this page is open\./);
  assert.match(componentSource, /getApexCockpitSpeechRecognitionCtor/);
  assert.match(componentSource, /webkitSpeechRecognition/);
  assert.match(componentSource, /cockpitBrowserTranscript/);
  assert.match(componentSource, /cockpitRecognitionStatus/);
  assert.match(componentSource, /Browser speech captions/);
  assert.match(componentSource, /Caption fallback ready/);
  assert.match(componentSource, /Live captions active/);
  assert.match(componentSource, /startCockpitSpeechRecognition/);
  assert.match(componentSource, /stopCockpitSpeechRecognition/);
  assert.match(componentSource, /buildApexCockpitVoiceHealth/);
  assert.match(componentSource, /Apex voice health and recovery/);
  assert.match(componentSource, /Apex live voice health/);
  assert.match(componentSource, /Voice Health/);
  assert.match(componentSource, /Recover Voice/);
  assert.match(componentSource, /recoverCockpitVoice/);
  assert.match(componentSource, /Captions recovering/);
  assert.match(componentSource, /server transcription fallback/);
  assert.match(componentSource, /co-apex-life-orbit/);
  assert.match(componentSource, /co-apex-cockpit-mobile-response/);
  assert.match(componentSource, /co-apex-cockpit-main-response/);
  assert.match(componentSource, /Apex visible response/);
  assert.match(componentSource, /co-apex-cockpit-side-rail/);
  assert.match(utilSource, /buildApexLiveOperatorModeState/);
  assert.match(utilSource, /liveOperatorMode/);
  assert.match(utilSource, /Body-first review-first operator/);
  assert.match(utilSource, /live-loop-save/);
  assert.match(utilSource, /live-loop-interrupt/);
  assert.match(utilSource, /live-loop-command-run/);
  assert.match(utilSource, /live-loop-judge/);
  assert.match(utilSource, /live-loop-follow-up/);
  assert.match(utilSource, /operatorJudgmentRows/);
  assert.match(utilSource, /Apex Live Operator judgment/);
  assert.match(utilSource, /next-turn prompts/);
  assert.match(utilSource, /voice health recovery/);
  assert.match(utilSource, /voice health recovery lane/);
  assert.match(utilSource, /Natural command/);
  assert.match(utilSource, /natural-command autopilot/);
  assert.match(utilSource, /live-loop-cycle/);
  assert.match(utilSource, /live-loop-auto-prep/);
  assert.match(utilSource, /live-loop-proof-check/);
  assert.match(utilSource, /summarizeAutonomyRunProgress/);
  assert.match(utilSource, /Report-ready/);
  assert.match(utilSource, /Barge-in memory/);
  assert.match(utilSource, /surfaced proactive check-ins can draft suggested memory/);
  assert.match(utilSource, /proactive check-in memory/);
  assert.match(utilSource, /Remembered check-ins/);
  assert.match(utilSource, /live-gap-execution/);
  assert.match(cssSource, /\.co-apex-cockpit-side-rail/);
  assert.match(cssSource, /max-width: 1279px/);
  assert.match(cssSource, /min-width: 1280px/);
  assert.match(cssSource, /\.co-apex-cockpit-screen--focus \.co-apex-cockpit-side-rail/);
  assert.match(cssSource, /\.co-apex-cockpit-screen--focus \.co-apex-cockpit-main-grid/);
  assert.match(cssSource, /\.co-apex-cockpit-screen--immersive \.co-apex-life-body/);
  assert.match(cssSource, /min-height: clamp\(31rem, 64vh, 42rem\)/);
  assert.match(cssSource, /\.co-apex-cockpit-screen--console \.co-apex-life-body/);
  assert.match(cssSource, /\.co-apex-cockpit-screen--spotlight \.co-apex-life-body/);
  assert.match(cssSource, /\.co-apex-cockpit-screen--spotlight \.co-apex-cockpit-live-console/);
  assert.match(cssSource, /\.co-apex-cockpit-mobile-dock/);
  assert.match(cssSource, /height: clamp\(16\.5rem, 44dvh, 23rem\)/);
  assert.match(cssSource, /max-height: clamp\(16\.5rem, 44dvh, 23rem\)/);
  assert.match(cssSource, /min-width: 768px\) and \(max-width: 1279px/);
  assert.match(cssSource, /height: clamp\(16rem, 32dvh, 23rem\)/);
  assert.match(cssSource, /max-height: clamp\(16rem, 32dvh, 23rem\)/);
  assert.match(cssSource, /\.co-apex-cockpit-screen--spotlight \.co-apex-cockpit-frame/);
  assert.match(cssSource, /\.co-apex-cockpit-screen--spotlight \.co-apex-cockpit-content-shell/);
  assert.match(cssSource, /\.co-apex-cockpit-screen--spotlight \.co-apex-cockpit-main-grid/);
  assert.match(cssSource, /grid-template-rows: auto !important/);
  assert.match(cssSource, /grid-auto-rows: auto/);
  assert.match(cssSource, /\.co-apex-cockpit-screen--spotlight \.co-apex-cockpit-focus-center[\s\S]*overflow: visible !important/);
  assert.match(cssSource, /\.co-apex-cockpit-screen--spotlight \.co-apex-cockpit-main-response/);
  assert.match(cssSource, /\.co-apex-cockpit-screen--spotlight \.co-apex-cockpit-console-tabs/);
  assert.match(cssSource, /\.co-apex-cockpit-screen--spotlight \.co-apex-cockpit-operator-metrics/);
  assert.match(cssSource, /\.co-apex-cockpit-screen--full-console \.co-apex-cockpit-live-console/);
  assert.match(cssSource, /\.co-apex-cockpit-focus-drawer/);
  assert.match(componentSource, /key: "hearing"/);
  assert.match(componentSource, /No Sends/);
  assert.match(componentSource, /No Deploys/);
  assert.match(componentSource, /VoiceTranscriptPanel/);
  assert.match(componentSource, /Use in Ask Apex/);
  assert.match(componentSource, /Open voice/);
  assert.match(componentSource, /canToggleRecording/);
  assert.match(componentSource, /canToggleCockpitVoice/);
  assert.match(componentSource, /openCockpitVoiceSession/);
  assert.match(componentSource, /pauseCockpitVoiceSession/);
  assert.match(componentSource, /transcribeCockpitVoiceBlob/);
  assert.match(componentSource, /unlockBrowserAudio/);
  assert.match(componentSource, /playSilentUnlockBuffer/);
  assert.match(componentSource, /playApexVoiceAudio/);
  assert.match(componentSource, /decodeApexVoiceAudioBuffer/);
  assert.match(componentSource, /speechSynthesis\.resume/);
  assert.match(componentSource, /utterance\.volume = 1/);
  assert.match(componentSource, /createBufferSource/);
  assert.match(componentSource, /decodeAudioData/);
  assert.match(componentSource, /playsInline/);
  assert.match(componentSource, /createObjectURL/);
  assert.match(componentSource, /answerAudioUnlockedRef/);
  assert.match(componentSource, /navigator\.mediaDevices\?\.getUserMedia/);
  assert.match(componentSource, /echoCancellation: true/);
  assert.match(componentSource, /noiseSuppression: true/);
  assert.match(componentSource, /autoGainControl: true/);
  assert.match(componentSource, /onClick=\{recording \? closeVoiceSession : openVoiceSession\}/);
  assert.match(componentSource, /onClick=\{cockpitRecording \? pauseCockpitVoiceSession : cockpitSpeaking \? \(\) => interruptCockpitVoicePlayback\("manual-button"\) : \(\) => openCockpitVoiceSession\(\{ automatic: false \}\)\}/);
  assert.doesNotMatch(componentSource, />9:41 AM</);
  assert.doesNotMatch(componentSource, /value=\{memoryCount \|\| 128\}/);
  assert.match(componentSource, /Close & transcribe/);
  assert.match(componentSource, /Voice command review/);
  assert.match(componentSource, /Speak answer/);
  assert.match(componentSource, /Stop voice/);
  assert.match(componentSource, /speakApexOsVoice/);
  assert.match(componentSource, /transcribeApexOsVoice/);
  assert.match(componentSource, /Approval Command Center/);
  assert.match(componentSource, /Approval Packet Drafts/);
  assert.match(componentSource, /ApprovalPacketDraftPanel/);
  assert.match(componentSource, /createApexOsApprovalPacket/);
  assert.match(componentSource, /getApexOsApprovalPackets/);
  assert.match(componentSource, /updateApexOsApprovalPacket/);
  assert.match(componentSource, /Draft packet/);
  assert.match(componentSource, /Record approval/);
  assert.match(componentSource, /Packet approval only/);
  assert.match(componentSource, /Approval Templates/);
  assert.match(componentSource, /Approval Controls/);
  assert.match(componentSource, /Approval Sources/);
  assert.match(componentSource, /Execute locked/);
  assert.match(componentSource, /Release Monitoring/);
  assert.match(componentSource, /ReleaseMonitoringPanel/);
  assert.match(componentSource, /Refresh monitoring/);
  assert.match(componentSource, /releaseMonitoringRowsWithSnapshot/);
  assert.match(componentSource, /App Build Awareness/);
  assert.match(componentSource, /BuildAwarenessPanel/);
  assert.match(componentSource, /getApexOsBuildAwareness/);
  assert.match(componentSource, /Changed File Map/);
  assert.match(componentSource, /Frozen Phase Map/);
  assert.match(componentSource, /Source Links/);
  assert.match(componentSource, /Daily Briefing/);
  assert.match(componentSource, /DailyBriefingPanel/);
  assert.match(componentSource, /getApexOsDailyBriefing/);
  assert.match(componentSource, /saveApexOsDailyBriefingSnapshot/);
  assert.match(componentSource, /Save snapshot/);
  assert.match(componentSource, /Changed Since Last Briefing/);
  assert.match(componentSource, /Briefing History/);
  assert.match(componentSource, /Briefing Locks/);
  assert.match(componentSource, /Personal Operating Layer/);
  assert.match(componentSource, /PersonalOperatingLayerPanel/);
  assert.match(componentSource, /Draft preference/);
  assert.match(componentSource, /Load preferences/);
  assert.match(componentSource, /No hidden tracking/);
  assert.match(componentSource, /John Preferences/);
  assert.match(componentSource, /Work Style Memory/);
  assert.match(componentSource, /Communication Preferences/);
  assert.match(componentSource, /Daily Focus/);
  assert.match(componentSource, /Do Not Distract Unless/);
  assert.match(componentSource, /Background Vs Check-In/);
  assert.match(componentSource, /Personal Privacy Locks/);
  assert.match(componentSource, /Release Readiness Packet/);
  assert.match(componentSource, /Monitoring Locks/);
  assert.match(componentSource, /Business Command Center/);
  assert.match(componentSource, /Business Gates/);
  assert.match(componentSource, /Launch \/ Founder Demo/);
  assert.match(componentSource, /Business Briefing/);
  assert.match(componentSource, /Business Source Memory/);
  assert.match(componentSource, /Business Task Drafts/);
  assert.match(componentSource, /Business Approval Drafts/);
  assert.match(utilSource, /APEX_OS_BUSINESS_TASK_DRAFT_ROWS/);
  assert.match(utilSource, /APEX_OS_BUSINESS_APPROVAL_DRAFT_ROWS/);
  assert.match(utilSource, /buildBusinessMemoryRows/);
  assert.match(componentSource, /QA \/ Security Hardening/);
  assert.match(componentSource, /Hardening Locks/);
  assert.match(componentSource, /Completion Audit/);
  assert.match(componentSource, /Security Proof Sources/);
  assert.match(componentSource, /Finished Apex OS/);
  assert.match(componentSource, /Day-to-Day Run Loop/);
  assert.match(componentSource, /Completion Freeze/);
  assert.match(componentSource, /Still Blocked/);
  assert.match(utilSource, /production-preview-smoke/);
  assert.match(utilSource, /docs-memory-drift/);
  assert.match(utilSource, /apex-os-kill-switch/);
  assert.match(utilSource, /APEX_OS_FINISHED_CAPABILITY_ROWS/);
  assert.match(utilSource, /APEX_OS_FINISHED_BLOCKED_ACTION_ROWS/);
  assert.match(componentSource, /What John decided/);
  assert.match(componentSource, /Launch Readiness/);
  assert.match(componentSource, /Release Desk/);
  assert.match(componentSource, /ReleaseDeskPanel/);
  assert.match(componentSource, /Refresh release desk/);
  assert.match(componentSource, /Deploy approved locked/);
  assert.match(componentSource, /Production Preview Status/);
  assert.match(componentSource, /Deploy History/);
  assert.match(componentSource, /Deploy Approved Flow/);
  assert.match(componentSource, /Release Safety Summary/);
  assert.match(utilSource, /export function deriveApexControlRoomState\b/);
  assert.match(utilSource, /export function buildReleaseDesk\b/);
  assert.match(utilSource, /deriveAgentOsInternalTaskOptions/);
  assert.match(utilSource, /deriveLaunchReadinessEvidenceState/);
  assert.match(utilSource, /getReleaseSafetySections/);
  assert.match(utilSource, /function buildPhase3AggregatorState/);
  assert.match(utilSource, /buildApexOsBuildAwarenessSnapshot/);
  assert.match(utilSource, /restrictedApexOsBuildAwarenessSnapshot/);
  assert.match(utilSource, /APEX_OS_DERIVED_STATE_META/);
  assert.match(utilSource, /withDerivedStateMeta/);
  assert.match(utilSource, /APEX_OS_DECISION_MEMORY_SEED/);
  assert.match(utilSource, /APEX_OS_DECISION_CATEGORIES/);
  assert.match(utilSource, /APEX_OS_OPERATING_RULES/);
  assert.match(utilSource, /function buildAgentWorkQueue/);
  assert.match(utilSource, /buildApexOsAgentControlPlane/);
  assert.match(utilSource, /function buildExecutionHandoffState/);
  assert.match(utilSource, /runStatusTone/);
  assert.match(utilSource, /APEX_OS_KNOWLEDGE_VAULT_CATEGORIES/);
  assert.match(utilSource, /APEX_OS_KNOWLEDGE_VAULT_SAFETY_RULES/);
  assert.match(utilSource, /function buildKnowledgeVaultState/);
  assert.match(utilSource, /buildApexOsKnowledgeIntelligence/);
  assert.match(utilSource, /APEX_OS_CHAT_CONTEXTS/);
  assert.match(utilSource, /APEX_OS_CHAT_ACTION_LOCKS/);
  assert.match(utilSource, /function buildAskApexChatState/);
  assert.match(utilSource, /APEX_OS_VOICE_MODES/);
  assert.match(utilSource, /APEX_OS_VOICE_SAFETY_GATES/);
  assert.match(utilSource, /function buildVoiceInterfaceState/);
  assert.match(utilSource, /APEX_OS_APPROVAL_PACKET_FIELDS/);
  assert.match(utilSource, /APEX_OS_APPROVAL_CONTROL_LOCKS/);
  assert.match(utilSource, /function buildApprovalCommandCenterState/);
  assert.match(utilSource, /APEX_OS_RELEASE_MONITORING_CHECKS/);
  assert.match(utilSource, /APEX_OS_RELEASE_MONITORING_LOCKS/);
  assert.match(utilSource, /function buildReleaseMonitoringState/);
  assert.match(utilSource, /APEX_OS_PERSONAL_OPERATING_SEED_ROWS/);
  assert.match(utilSource, /APEX_OS_PERSONAL_WORK_STYLE_ROWS/);
  assert.match(utilSource, /APEX_OS_PERSONAL_COMMUNICATION_ROWS/);
  assert.match(utilSource, /APEX_OS_PERSONAL_DAILY_FOCUS_ROWS/);
  assert.match(utilSource, /APEX_OS_PERSONAL_DISTRACTION_RULE_ROWS/);
  assert.match(utilSource, /APEX_OS_PERSONAL_BACKGROUND_ROWS/);
  assert.match(utilSource, /APEX_OS_PERSONAL_CHECK_IN_ROWS/);
  assert.match(utilSource, /APEX_OS_PERSONAL_PRIVACY_LOCKS/);
  assert.match(utilSource, /function buildPersonalOperatingLayerState/);
  assert.match(utilSource, /APEX_OS_BUSINESS_QUEUE_ROWS/);
  assert.match(utilSource, /APEX_OS_BUSINESS_GATES/);
  assert.match(utilSource, /function buildBusinessCommandCenterState/);
  assert.match(utilSource, /APEX_OS_QA_SECURITY_EVIDENCE_ROWS/);
  assert.match(utilSource, /APEX_OS_QA_SECURITY_LOCKS/);
  assert.match(utilSource, /function buildQaSecurityHardeningState/);
});
