import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

test("Apex Avatar Lab is wired as a private Three.js route", () => {
  const appSource = fs.readFileSync(new URL("./App.jsx", import.meta.url), "utf8");
  const componentSource = fs.readFileSync(new URL("./apex-avatar-lab-components.jsx", import.meta.url), "utf8");
  const cssSource = fs.readFileSync(new URL("./index.css", import.meta.url), "utf8");

  assert.match(appSource, /const ApexAvatarLabPage = lazyRouteComponent\(\(\) => import\("\.\/apex-avatar-lab-components"\), "ApexAvatarLabPage"\);/);
  assert.match(appSource, /\{ id: "apexAvatarLab", label: "Avatar Lab", icon: "spark" \}/);
  assert.match(appSource, /if \(active === "apexAvatarLab"\) return <ApexAvatarLabPage \{\.\.\.props\}\s*\/>;/);
  assert.match(appSource, /active === "apexControlRoom" \|\| active === "apexAvatarLab"/);
  assert.doesNotMatch(appSource, /isApexControlRoomRoute/);

  assert.match(componentSource, /import \* as THREE from "three";/);
  assert.match(componentSource, /export function ApexAvatarLabPage\b/);
  assert.match(componentSource, /function ApexAvatarLabScene\b/);
  assert.match(componentSource, /new THREE\.WebGLRenderer/);
  assert.match(componentSource, /GLTFLoader/);
  assert.match(componentSource, /APEX_AVATAR_MODEL_URL/);
  assert.match(componentSource, /apex-intelligence-live-web-1536\.glb/);
  assert.match(componentSource, /APEX_AVATAR_MASTER_MODEL_URL/);
  assert.match(componentSource, /apex-intelligence-idle-app-ready\.glb/);
  assert.match(componentSource, /APEX_AVATAR_FALLBACK_MODEL_URL/);
  assert.match(componentSource, /apex-assistant\.glb/);
  assert.match(componentSource, /APEX_AVATAR_CLIP_BY_MODE/);
  assert.match(componentSource, /APEX_AVATAR_REQUIRED_CLIPS/);
  ["Idle", "Listening", "Hearing", "Thinking", "Speaking", "Blocked", "Alert"].forEach((clipName) => {
    assert.match(componentSource, new RegExp(`"${clipName}"`));
  });
  assert.match(componentSource, /cloneImportedMaterial/);
  assert.match(componentSource, /new THREE\.AnimationMixer/);
  assert.match(componentSource, /crossFadeTo\(nextAction/);
  assert.doesNotMatch(componentSource, /new THREE\.Clock/);
  assert.match(componentSource, /preserveDrawingBuffer: true/);
  assert.match(componentSource, /createGlowMaterial/);
  assert.match(componentSource, /createExtrudedShapeGeometry/);
  assert.match(componentSource, /facetedHelmetGroup/);
  assert.match(componentSource, /angularTorsoGeometry/);
  assert.match(componentSource, /reactorCoreGeometry/);
  assert.match(componentSource, /silhouetteGroup/);
  assert.match(componentSource, /mouthEnvelope/);
  assert.match(componentSource, /smoothedEnergy/);
  assert.match(componentSource, /root\.userData\.mobile/);
  assert.match(componentSource, /mobileFrame \? 0\.58 : 1/);
  assert.match(componentSource, /THREE\.MathUtils\.lerp/);
  assert.match(componentSource, /faceDetailGroup/);
  assert.match(componentSource, /armorDetailGroup/);
  assert.match(componentSource, /voiceRingGroup/);
  assert.match(componentSource, /thoughtOrbitGroup/);
  assert.match(componentSource, /safetyLockGroup/);
  assert.match(componentSource, /ApexOperatorLightRig/);
  assert.match(componentSource, /assetMouthBars/);
  assert.match(componentSource, /assetBaseRings/);
  assert.match(componentSource, /assetCoreDot/);
  assert.match(componentSource, /leftChestPlate/);
  assert.match(componentSource, /jawArc/);
  assert.match(componentSource, /Operator Lab/);
  assert.match(componentSource, /Apex Intelligence 01/);
  assert.match(componentSource, /125k/);
  assert.match(componentSource, /10\.9 MB/);
  assert.match(componentSource, /1536 runtime/);
  assert.match(componentSource, /7 state clips/);
  assert.match(componentSource, /data-avatar-lab-canvas="true"/);
  assert.match(componentSource, /aria-label="Apex Avatar Lab Three\.js hologram scene"/);
  assert.match(componentSource, /AVATAR_MODE_ORDER/);
  assert.match(componentSource, /Voice Energy/);
  assert.match(componentSource, /Scan Depth/);
  assert.match(componentSource, /Data Density/);
  assert.match(componentSource, /Auto Pulse/);
  assert.match(componentSource, /HUD Shell/);
  assert.match(componentSource, /Particles/);
  assert.match(componentSource, /setActive\("apexControlRoom"\)/);

  assert.match(cssSource, /\.co-apex-avatar-lab\s*\{/);
  assert.match(cssSource, /\.co-apex-avatar-lab-scene\s*\{[\s\S]*position: fixed;/);
  assert.match(cssSource, /\.co-apex-avatar-lab-scene canvas\s*\{[\s\S]*width: 100%;[\s\S]*height: 100%;[\s\S]*min-height: 100dvh;/);
  assert.match(cssSource, /\.co-apex-avatar-lab-mode-dock\s*\{/);
  assert.match(cssSource, /\.co-apex-avatar-lab-panel--left/);
  assert.match(cssSource, /\.co-apex-avatar-lab-panel--right/);
  assert.match(cssSource, /body:has\(\.co-apex-avatar-lab\) nav\.co-mobile-bottom-nav\.co-apex-mobile-bottom-nav/);
  assert.match(cssSource, /@media \(max-width: 767px\)[\s\S]*\.co-apex-avatar-lab-panel\s*\{[\s\S]*width: 100%;/);
  assert.match(cssSource, /@media \(max-width: 767px\)[\s\S]*grid-template-columns: repeat\(3, minmax\(0, 1fr\)\);/);
  assert.match(cssSource, /@media \(max-width: 767px\)[\s\S]*margin-bottom: clamp\(180px, 28dvh, 260px\);/);
  assert.match(cssSource, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.co-apex-avatar-lab-mode/);
});
