import assert from "node:assert/strict";
import test from "node:test";

import {
  buildLaunchReadinessEvidencePacket,
  deriveLaunchReadinessEvidenceState,
} from "./launch-readiness-utils.js";

test("launch readiness evidence stays locked for public launch and production actions", () => {
  const state = deriveLaunchReadinessEvidenceState({
    launchGate: { guidedDemoReady: true },
    backup: { backupVerified: true, restoreVerified: true },
    productionRelease: { releaseProcessReady: true },
    productionAuth: { workflowGuarded: true, enabled: false },
    monitoring: { baselineReady: true },
    support: { processReady: true },
    legal: { claimsVerified: true, legalApproved: false },
    publicLaunch: { selfServeReady: false, publicLaunchApproved: false },
  });

  assert.equal(state.status, "Launch locked");
  assert.equal(state.readyCount, 5);
  assert.equal(state.blockedCount, 3);
  assert.equal(state.gates.find((gate) => gate.id === "production-auth").status, "Blocked");
  assert.match(state.gates.find((gate) => gate.id === "production-auth").blockers.join(" "), /intentionally not enabled/i);
  assert.equal(state.gates.find((gate) => gate.id === "public-launch").ready, false);
  assert.match(state.hardLocks.join(" "), /No deploy/i);
  assert.match(state.hardLocks.join(" "), /No checkout/i);
});

test("launch readiness evidence packet is copy-only and avoids approval claims", () => {
  const state = deriveLaunchReadinessEvidenceState({
    launchGate: { guidedDemoReady: true },
    backup: { backupVerified: false, restoreVerified: true },
    productionRelease: { releaseProcessReady: false },
    productionAuth: { workflowGuarded: true, enabled: false },
    monitoring: { baselineReady: false },
    support: { processReady: true },
    legal: { claimsVerified: true, legalApproved: false },
  });
  const packet = buildLaunchReadinessEvidencePacket(state, {
    companyName: "ABC Builders",
    userName: "Alex Owner",
    generatedAt: "2026-05-30T12:00:00.000Z",
  });

  assert.match(packet, /Apex HQ Launch Readiness Evidence Packet/);
  assert.match(packet, /Workspace: ABC Builders/);
  assert.match(packet, /Generated by: Alex Owner/);
  assert.match(packet, /Status: Launch locked/);
  assert.match(packet, /Run npm\.cmd run verify:backup/);
  assert.match(packet, /copy-only/i);
  assert.match(packet, /did not deploy, enable public signup, run production auth smoke/i);
  assert.doesNotMatch(packet, /public launch approved|legal approved|production auth enabled/i);
});
