import assert from "node:assert/strict";
import test from "node:test";

import { buildPrintDocumentHtml, deriveDailyReportPrintPacket, deriveEstimatePrintPacket, deriveJobPrintPacket } from "./print-packets.js";

test("daily report print packet includes core report fields and related records", () => {
  const packet = deriveDailyReportPrintPacket({
    companyName: "Concrete Ops Demo",
    companyProfile: {
      businessPhone: "(503) 555-0100",
      businessEmail: "office@concreteopsdemo.com",
      website: "https://concreteopsdemo.com",
      serviceArea: "Portland metro",
    },
    printPacketFooter: "Generated by Concrete Ops for job documentation, field reports, and closeout records.",
    printPacketDisclaimer: "Internal job documentation. Review all details before sharing outside the company.",
    report: {
      id: "R-1",
      jobId: "J-1",
      reportDate: "2026-04-26",
      status: "submitted",
      createdBy: "U-1",
      createdByName: "Demo Foreman",
      submittedAt: "2026-04-26T16:30:00Z",
      reviewedAt: "2026-04-26T18:00:00Z",
      crewSummary: "2 finishers and 1 foreman",
      workPerformed: "Placed and finished the front walk.",
      delays: "None",
      safetyNotes: "PPE check completed.",
      equipmentUsed: "Bull float and saw",
      materialNotes: "Fiber mix",
      concretePoured: true,
      yardsPoured: 8.5,
      weather: "Cloudy",
      visitorNotes: "Homeowner walkthrough complete.",
      inspectionNotes: "City inspection passed.",
      generalNotes: "Ready for cure.",
      timeSummary: { totalEntries: 3, totalMinutes: 480, breakMinutes: 30 },
      crewAssignments: [{ id: "A-1", userId: "U-1", userName: "Demo Foreman", roleOnJob: "foreman" }],
      job: { id: "J-1", title: "Martinez Driveway", address: "123 Demo Ln" },
    },
    deliveryTickets: [{ id: "DT-1", jobId: "J-1", reportId: "R-1", supplier: "Knife River", ticketNumber: "T-42", yardsDelivered: 8.5 }],
    uploads: [{ id: "UPL-1", jobId: "J-1", reportId: "R-1", fileName: "finish.jpg", caption: "Finished broom finish", uploadedAt: "2026-04-26T18:15:00Z" }],
  });

  assert.equal(packet.title, "Daily Report Packet");
  assert.equal(packet.sections.some((section) => section.title === "Work Performed"), true);
  assert.equal(packet.sections.some((section) => section.title === "Related Delivery Tickets"), true);
  assert.equal(packet.sections.some((section) => section.title === "Related Uploads / Photos"), true);

  const html = buildPrintDocumentHtml(packet);
  assert.match(html, /Concrete Ops Demo/);
  assert.match(html, /Martinez Driveway/);
  assert.match(html, /Placed and finished the front walk\./);
  assert.match(html, /Knife River/);
  assert.match(html, /Finished broom finish/);
  assert.match(html, /\(503\) 555-0100/);
  assert.match(html, /office@concreteopsdemo\.com/);
  assert.match(html, /Portland metro/);
  assert.match(html, /Generated by Concrete Ops for job documentation, field reports, and closeout records\./);
  assert.match(html, /Internal job documentation\. Review all details before sharing outside the company\./);
});

test("job packet includes linked operational records for office packets", () => {
  const packet = deriveJobPrintPacket({
    companyName: "Concrete Ops Demo",
    companyProfile: {
      businessEmail: "office@concreteopsdemo.com",
      website: "https://concreteopsdemo.com",
      businessAddress: "123 Demo Ln, Salem, OR 97301",
      licenseText: "CCB #123456 · Bonded and insured.",
    },
    printPacketFooter: "Generated by Concrete Ops for job documentation, field reports, and closeout records.",
    printPacketDisclaimer: "Internal job documentation. Review all details before sharing outside the company.",
    packetMode: "internal",
    job: {
      id: "J-1",
      title: "Martinez Driveway",
      customer: "Martinez Residence",
      address: "123 Demo Ln",
      status: "billing_ready",
      scheduledStart: "2026-04-26T07:00:00Z",
      scopeSummary: "Replace cracked driveway panels.",
      notes: "Customer asked for extra cleanup.",
      fieldNotes: "Crew staged forms on the west side.",
      assignments: [{ id: "A-1", userId: "U-1", userName: "Demo Foreman", roleOnJob: "foreman" }],
    },
    dailyReports: [{ id: "R-1", jobId: "J-1", reportDate: "2026-04-26", status: "reviewed", createdByName: "Demo Foreman", workPerformed: "Removed and repoured the driveway." }],
    uploads: [{ id: "UPL-1", jobId: "J-1", fileName: "before.jpg", caption: "Before demo photo" }],
    prePourChecklists: [{ id: "PP-1", jobId: "J-1", status: "reviewed", items: [{ label: "Forms set", status: "checked" }] }],
    postPourChecklists: [{ id: "POP-1", jobId: "J-1", status: "completed", items: [{ label: "Completion photos taken", status: "checked" }] }],
    deliveryTickets: [{ id: "DT-1", jobId: "J-1", supplier: "Knife River", ticketNumber: "T-42", yardsDelivered: 8 }],
    changeOrderRequests: [{ id: "CO-1", jobId: "J-1", reason: "Extra apron width", status: "under_review", scopeDescription: "Add 2 feet to the apron", officeNotes: "Price with premium broom finish." }],
    calculatorResults: [{ id: "CALC-1", jobId: "J-1", calculatorType: "slab", summary: "Driveway slab", cubicYards: 7.2, cubicYardsWithWaste: 7.92 }],
    safetyIncidents: [{ id: "SI-1", jobId: "J-1", title: "Loose form stake", severity: "low", status: "resolved", description: "Stake reset before pour." }],
    toolChecklists: [{ id: "TC-1", jobId: "J-1", title: "Pour day tools", status: "submitted", items: [{ name: "Bull float", status: "on_site" }] }],
  });

  const html = buildPrintDocumentHtml(packet);
  assert.match(html, /Martinez Residence/);
  assert.match(html, /Extra apron width/);
  assert.match(html, /Price with premium broom finish\./);
  assert.match(html, /Loose form stake/);
  assert.match(html, /Driveway slab/);
  assert.match(html, /office@concreteopsdemo\.com/);
  assert.match(html, /123 Demo Ln, Salem, OR 97301/);
  assert.match(html, /CCB #123456/);
});

test("field-safe packet excludes office-only notes and safety incidents", () => {
  const packet = deriveJobPrintPacket({
    packetMode: "field_safe",
    job: {
      id: "J-1",
      title: "Martinez Driveway",
      customer: "Martinez Residence",
      notes: "Office-only cleanup commitment.",
      fieldNotes: "Crew staged forms on site.",
      status: "in_progress",
    },
    changeOrderRequests: [{ id: "CO-1", jobId: "J-1", reason: "Extra apron width", status: "requested", scopeDescription: "Add 2 feet to the apron", officeNotes: "Price with premium broom finish." }],
    safetyIncidents: [{ id: "SI-1", jobId: "J-1", title: "Loose form stake", severity: "low", status: "resolved", description: "Stake reset before pour." }],
  });

  const html = buildPrintDocumentHtml(packet);
  assert.doesNotMatch(html, /Office-only cleanup commitment\./);
  assert.match(html, /Crew staged forms on site\./);
  assert.doesNotMatch(html, /Price with premium broom finish\./);
  assert.doesNotMatch(html, /Loose form stake/);
});

test("estimate print packet includes customer-facing estimate details without internal notes", () => {
  const packet = deriveEstimatePrintPacket({
    companyName: "Concrete Ops Demo",
    companyProfile: {
      logoInitials: "COD",
      businessPhone: "(503) 555-0100",
      businessEmail: "office@concreteopsdemo.com",
      website: "https://concreteopsdemo.com",
      businessAddress: "123 Demo Ln, Salem, OR 97301",
      serviceArea: "Salem and Portland metro",
      licenseText: "CCB #123456 - Bonded and insured.",
    },
    printPacketFooter: "Generated by Concrete Ops for job documentation, field reports, and closeout records.",
    printPacketDisclaimer: "Internal job documentation. Review all details before sharing outside the company.",
    estimate: {
      id: "EST-1",
      title: "Martinez Driveway Proposal",
      status: "sent",
      createdAt: "2026-04-26T16:30:00Z",
      scopeSummary: [
        "Scope of Work:",
        "Replace cracked driveway panels and pour a broom-finish apron.",
        "",
        "Inclusions:",
        "Demo, haul-off, forming, placement, and broom finish.",
        "",
        "Exclusions:",
        "Permit fees and utility relocation.",
        "",
        "Assumptions / Clarifications:",
        "Customer will provide clear access before the pour.",
      ].join("\n"),
      internalNotes: [
        "Office-only follow-up note.",
        "[Concrete Ops GC Packet Lite]",
        JSON.stringify({
          proposalCoverNote: "Thank you for the opportunity to price this work.",
          proposalSummary: "GC-facing commercial concrete proposal summary.",
          qualifications: "Proposal is based on Addendum 01.",
          scheduleNotes: "Schedule will be coordinated with the GC.",
          addendaRfiReferences: "RFI 03 and Addendum 01 reviewed.",
          gcReviewNotes: "Office-only GC follow-up.",
          internalPacketNotes: "Internal packet assembly note.",
        }),
        "[/Concrete Ops GC Packet Lite]",
        "[Concrete Ops Estimate Backup]",
        JSON.stringify({ notes: "Private SOV backup" }),
        "[/Concrete Ops Estimate Backup]",
        "[Concrete Ops Sent Proposal History]",
        JSON.stringify([{ snapshotId: "snap-private", notes: "Private sent history" }]),
        "[/Concrete Ops Sent Proposal History]",
      ].join("\n"),
      customerNotes: [
        "Customer Notes / Terms:",
        "Estimate is valid for 30 days.",
        "",
        "Alternates:",
        "- [optional] Stamped border | Amount: $1,250.00 | Description: Add stamped border.",
        "- [accepted] Thicker driveway edge | Amount: $900.00",
        "- [excluded] Extra sawcutting | Amount: $300.00",
        "",
        "Optional Add-ons:",
        "- [selected] Sealer | Amount: $450.00",
      ].join("\n"),
      customer: { name: "Martinez Residence" },
      lead: { customer: "Martinez Residence", project: "Driveway replacement estimate" },
      items: [
        { description: "Demo and haul off", quantity: 1, unit: "LS", unitPrice: 1850 },
        { description: "Concrete placement", quantity: 9, unit: "yd", unitPrice: 215 },
      ],
      taxRate: 0,
      feesTotal: 125,
    },
  });

  const html = buildPrintDocumentHtml(packet);
  assert.match(html, /Martinez Driveway Proposal/);
  assert.match(html, /Driveway replacement estimate/);
  assert.match(html, /Scope of Work/);
  assert.match(html, /Inclusions/);
  assert.match(html, /Exclusions/);
  assert.match(html, /Assumptions \/ Clarifications/);
  assert.match(html, /Demo, haul-off, forming, placement, and broom finish\./);
  assert.match(html, /Permit fees and utility relocation\./);
  assert.match(html, /Proposal Cover Note/);
  assert.match(html, /Thank you for the opportunity to price this work\./);
  assert.match(html, /Proposal Summary/);
  assert.match(html, /GC-facing commercial concrete proposal summary\./);
  assert.match(html, /Qualifications/);
  assert.match(html, /Proposal is based on Addendum 01\./);
  assert.match(html, /Schedule Notes/);
  assert.match(html, /Schedule will be coordinated with the GC\./);
  assert.match(html, /Addenda \/ RFI References/);
  assert.match(html, /RFI 03 and Addendum 01 reviewed\./);
  assert.match(html, /Demo and haul off/);
  assert.match(html, /Base Estimate Total/);
  assert.match(html, /Base estimate total/);
  assert.match(html, /Alternates/);
  assert.match(html, /Stamped border/);
  assert.match(html, /Thicker driveway edge/);
  assert.match(html, /Optional Add-ons/);
  assert.match(html, /Sealer/);
  assert.match(html, /Selected options total/);
  assert.match(html, /Total with selected options/);
  assert.match(html, /Estimate is valid for 30 days\./);
  assert.match(html, /COD/);
  assert.match(html, /\(503\) 555-0100/);
  assert.match(html, /office@concreteopsdemo\.com/);
  assert.match(html, /https:\/\/concreteopsdemo\.com/);
  assert.match(html, /123 Demo Ln, Salem, OR 97301/);
  assert.match(html, /Salem and Portland metro/);
  assert.match(html, /CCB #123456 - Bonded and insured\./);
  assert.match(html, /Generated by Concrete Ops for job documentation, field reports, and closeout records\./);
  assert.match(html, /Internal job documentation\. Review all details before sharing outside the company\./);
  assert.doesNotMatch(html, /Office-only follow-up note\./);
  assert.doesNotMatch(html, /Office-only GC follow-up/);
  assert.doesNotMatch(html, /Internal packet assembly note/);
  assert.doesNotMatch(html, /Private SOV backup/);
  assert.doesNotMatch(html, /Private sent history/);
  assert.doesNotMatch(html, /Concrete Ops GC Packet Lite/);
  assert.match(html, /@page \{ margin: 0\.5in; \}/);
  assert.match(html, /white-space: pre-line/);
  assert.match(html, /page-break-inside: avoid/);
  assert.match(html, /page-break-after: avoid/);
});

test("estimate print packet keeps old plain estimates readable", () => {
  const packet = deriveEstimatePrintPacket({
    estimate: {
      id: "EST-LEGACY",
      title: "Plain Estimate",
      scopeSummary: "Plain one-paragraph scope.",
      customerNotes: "Plain customer terms.",
      items: [],
    },
  });

  const html = buildPrintDocumentHtml(packet);
  assert.match(html, /Scope of Work/);
  assert.match(html, /Plain one-paragraph scope\./);
  assert.match(html, /Customer Notes \/ Terms/);
  assert.match(html, /Plain customer terms\./);
  assert.doesNotMatch(html, /Alternates/);
  assert.doesNotMatch(html, /Total with selected options/);
});

test("print packet helpers tolerate missing linked arrays and render clean empty states", () => {
  const reportPacket = deriveDailyReportPrintPacket({ companyName: "Concrete Ops Demo", report: null });
  const jobPacket = deriveJobPrintPacket({ companyName: "Concrete Ops Demo", job: { id: "J-1", title: "Empty Job", status: "draft" } });

  assert.match(buildPrintDocumentHtml(reportPacket), /No report selected/);
  assert.match(buildPrintDocumentHtml(jobPacket), /Nothing recorded\./);
});
