import assert from "node:assert/strict";
import test from "node:test";

import {
  buildPrintDocumentHtml,
  deriveChangeOrderPrintPacket,
  deriveDailyReportPrintPacket,
  deriveEstimateForemanHandoffPacket,
  deriveEstimatePrintPacket,
  deriveJobPrintPacket,
  deriveProofCloseoutPrintPacket,
} from "./print-packets.js";

test("daily report print packet includes core report fields and related records", () => {
  const packet = deriveDailyReportPrintPacket({
    companyName: "Apex HQ Demo",
    companyProfile: {
      logoInitials: "AHD",
      printPacketHeaderColor: "#1e293b",
      printPacketHeaderTextColor: "#ffffff",
      printPacketAccentColor: "#0ea5e9",
      dailyReportPacketCoverTitle: "Pour Day Report",
      dailyReportPacketCoverKicker: "Daily Field Report",
      dailyReportPacketTagline: "Production, tickets, crew time, and proof records ready for review.",
      dailyReportPacketStatementTitle: "Ready for job documentation.",
      dailyReportPacketStatementBody: "Work performed, field notes, delivery tickets, and proof photos are organized for closeout review.",
      dailyReportPacketReviewNote: "OFFICE_ONLY_SENTINEL margin target $12,000. See file:///C:/secret/report-margin.xlsx.",
      businessPhone: "(503) 555-0100",
      businessEmail: "office@apexhqdemo.com",
      website: "https://apexhqdemo.com",
      serviceArea: "Portland metro",
    },
    printPacketFooter: "Generated by Apex HQ for job documentation, field reports, and closeout records.",
    printPacketDisclaimer: "Internal job documentation. OFFICE_ONLY_SENTINEL Payment Terms: 50% deposit and legal terms apply. https://files.example.test/private/report.pdf",
    report: {
      id: "R-1",
      jobId: "J-1",
      reportDate: "2026-04-26",
      status: "submitted",
      createdBy: "U-1",
      createdByName: "Demo Foreman",
      submittedAt: "2026-04-26T16:30:00Z",
      reviewedAt: "2026-04-26T18:00:00Z",
      crewSummary: "2 finishers and 1 foreman\nOFFICE_ONLY_SENTINEL margin target $12,000. file:///C:/secret/report-margin.xlsx",
      workPerformed: "Placed and finished the front walk. Proof reference https://files.example.test/private/work.jpg",
      delays: "None\nPrice floor is $12,000.",
      safetyNotes: "PPE check completed. Payment Terms: 50% deposit.",
      equipmentUsed: "Bull float and saw. Office-only equipment charge.",
      materialNotes: "Fiber mix from approved ticket.",
      concretePoured: true,
      yardsPoured: 8.5,
      weather: "Cloudy",
      visitorNotes: "Homeowner walkthrough complete. Legal terms apply.",
      inspectionNotes: "City inspection passed. www.private-inspection.example/report",
      generalNotes: "Ready for cure. OFFICE_ONLY_SENTINEL private office backup.",
      timeSummary: { totalEntries: 3, totalMinutes: 480, breakMinutes: 30 },
      crewAssignments: [{ id: "A-1", userId: "U-1", userName: "Demo Foreman", roleOnJob: "foreman" }],
      job: { id: "J-1", title: "Martinez Driveway", address: "123 Demo Ln", customer: "Martinez Residence" },
    },
    deliveryTickets: [{
      id: "DT-1",
      jobId: "J-1",
      reportId: "R-1",
      supplier: "Knife River https://files.example.test/private/ticket",
      ticketNumber: "T-42",
      truckNumber: "Truck 7 file:///C:/secret/ticket.jpg",
      yardsDelivered: 8.5,
      psi: "4000",
      slump: "5",
    }],
    uploads: [{
      id: "UPL-1",
      jobId: "J-1",
      reportId: "R-1",
      fileName: "finish-photo-file:///C:/secret/finish.jpg",
      caption: "Finished broom finish https://files.example.test/private/finish.jpg",
      notes: "OFFICE_ONLY_SENTINEL margin photo note $12,000",
      uploadedAt: "2026-04-26T18:15:00Z",
      url: "https://files.example.test/private/finish.jpg",
    }],
  });

  assert.equal(packet.title, "Daily Report Packet");
  assert.equal(packet.sections.some((section) => section.title === "Work Performed"), true);
  assert.equal(packet.sections.some((section) => section.title === "Related Delivery Tickets"), true);
  assert.equal(packet.sections.some((section) => section.title === "Related Uploads / Photos"), true);

  const html = buildPrintDocumentHtml(packet);
  assert.match(html, /Professional Packet/);
  assert.match(html, /Field-safe packet/);
  assert.match(html, /Daily Field Report/);
  assert.match(html, /Pour Day Report/);
  assert.match(html, /Production, tickets, crew time, and proof records ready for review\./);
  assert.match(html, /Ready for job documentation\./);
  assert.match(html, /Work performed, field notes, delivery tickets, and proof photos are organized for closeout review\./);
  assert.match(html, /Restricted office details and private file links are excluded\./);
  assert.match(html, /Production log/);
  assert.match(html, /Crew and time/);
  assert.match(html, /Ticket trail/);
  assert.match(html, /Proof trail/);
  assert.match(html, /--packet-header: #1e293b/);
  assert.match(html, /--packet-accent: #0ea5e9/);
  assert.ok(html.indexOf('<section class="proposal-cover-page">') < html.indexOf('<header class="packet-header">'));
  assert.match(html, /Packet type/);
  assert.match(html, /Daily Report Packet Summary/);
  assert.match(html, /Proof photos/);
  assert.match(html, /Apex HQ Demo/);
  assert.match(html, /Martinez Driveway/);
  assert.match(html, /Apr 26, 2026/);
  assert.match(html, /Placed and finished the front walk\./);
  assert.match(html, /Knife River/);
  assert.match(html, /Finished broom finish/);
  assert.match(html, /Link tracked in Apex HQ\./);
  assert.match(html, /\(503\) 555-0100/);
  assert.match(html, /office@apexhqdemo\.com/);
  assert.match(html, /Portland metro/);
  assert.match(html, /Generated by Apex HQ for job documentation, field reports, and closeout records\./);
  assert.match(html, /Field-safe job documentation\. Restricted office details and private file links are excluded\./);
  assert.doesNotMatch(html, /Internal job documentation/);
  assert.doesNotMatch(html, /OFFICE_ONLY_SENTINEL/);
  assert.doesNotMatch(html, /margin target|margin photo note|Price floor|Office-only equipment charge|private office backup/i);
  assert.doesNotMatch(html, /invoice amount|balance due|pay application|attorney fees|contract terms|profit|labor cost|private note|SOV/i);
  assert.doesNotMatch(html, /\$12,000/);
  assert.doesNotMatch(html, /Payment Terms|50% deposit|legal terms apply/i);
  assert.doesNotMatch(html, /files\.example\.test\/private/);
  assert.doesNotMatch(html, /private-inspection\.example/);
  assert.doesNotMatch(html, /file:\/\//);
  assert.doesNotMatch(html, /C:\\secret|\\\\server\\share/);
  assert.doesNotMatch(html, /Â|Ã|â/);
});

test("job packet includes linked operational records for office packets", () => {
  const packet = deriveJobPrintPacket({
    companyName: "Apex HQ Demo",
    companyProfile: {
      logoInitials: "AHD",
      printPacketHeaderColor: "#0f172a",
      printPacketHeaderTextColor: "#ffffff",
      printPacketAccentColor: "#22c55e",
      jobPacketCoverTitle: "Operations Job Packet",
      jobPacketCoverKicker: "Closeout Job Packet",
      jobPacketTagline: "Proof, tickets, checklists, and change-order records ready for office review.",
      jobPacketStatementTitle: "Ready for operations review.",
      jobPacketStatementBody: "Job records, field reports, proof photos, tickets, closeout checks, and office review notes are organized for the operations team.",
      jobPacketReviewNote: "Internal packet. Review before sharing outside the company.",
      businessEmail: "office@apexhqdemo.com",
      website: "https://apexhqdemo.com",
      businessAddress: "123 Demo Ln, Salem, OR 97301",
      licenseText: "CCB #123456 · Bonded and insured.",
    },
    printPacketFooter: "Generated by Apex HQ for job documentation, field reports, and closeout records.",
    printPacketDisclaimer: "Internal job documentation. Review all details before sharing outside the company.",
    packetMode: "internal",
    job: {
      id: "J-1",
      title: "Martinez Driveway",
      customer: "Martinez Residence",
      address: "123 Demo Ln",
      status: "billing_ready",
      scheduledStart: "2026-04-26T07:00:00Z",
      scopeSummary: "Replace cracked driveway panels.",
      notes: "Customer asked for extra cleanup.",
      fieldNotes: "Crew staged forms on the west side.",
      assignments: [{ id: "A-1", userId: "U-1", userName: "Demo Foreman", roleOnJob: "foreman" }],
    },
    dailyReports: [{ id: "R-1", jobId: "J-1", reportDate: "2026-04-26", status: "reviewed", createdByName: "Demo Foreman", workPerformed: "Removed and repoured the driveway." }],
    uploads: [{ id: "UPL-1", jobId: "J-1", fileName: "before.jpg", caption: "Before demo photo" }],
    prePourChecklists: [{ id: "PP-1", jobId: "J-1", status: "reviewed", items: [{ label: "Forms set", status: "checked" }] }],
    postPourChecklists: [{ id: "POP-1", jobId: "J-1", status: "completed", items: [{ label: "Completion photos taken", status: "checked" }] }],
    deliveryTickets: [{ id: "DT-1", jobId: "J-1", supplier: "Knife River", ticketNumber: "T-42", yardsDelivered: 8 }],
    changeOrderRequests: [{ id: "CO-1", jobId: "J-1", reason: "Extra apron width", status: "under_review", scopeDescription: "Add 2 feet to the apron", officeNotes: "Price with premium broom finish." }],
    calculatorResults: [{ id: "CALC-1", jobId: "J-1", calculatorType: "slab", summary: "Driveway slab", cubicYards: 7.2, cubicYardsWithWaste: 7.92 }],
    safetyIncidents: [{ id: "SI-1", jobId: "J-1", title: "Loose form stake", severity: "low", status: "resolved", description: "Stake reset before pour." }],
    toolChecklists: [{ id: "TC-1", jobId: "J-1", title: "Pour day tools", status: "submitted", items: [{ name: "Bull float", status: "on_site" }] }],
  });

  const html = buildPrintDocumentHtml(packet);
  assert.match(html, /Internal review \/ closeout packet/);
  assert.match(html, /Closeout Job Packet/);
  assert.match(html, /Operations Job Packet/);
  assert.match(html, /Proof, tickets, checklists, and change-order records ready for office review\./);
  assert.match(html, /Ready for operations review\./);
  assert.match(html, /Internal packet\. Review before sharing outside the company\./);
  assert.match(html, /Job control/);
  assert.match(html, /Change-order view/);
  assert.match(html, /--packet-header: #0f172a/);
  assert.match(html, /--packet-accent: #22c55e/);
  assert.ok(html.indexOf('<section class="proposal-cover-page">') < html.indexOf('<header class="packet-header">'));
  assert.match(html, /Packet Review Summary/);
  assert.match(html, /Proof \/ Closeout Evidence/);
  assert.match(html, /Change Order Packet/);
  assert.match(html, /Martinez Residence/);
  assert.match(html, /Extra apron width/);
  assert.match(html, /Price with premium broom finish\./);
  assert.match(html, /Loose form stake/);
  assert.match(html, /Driveway slab/);
  assert.match(html, /office@apexhqdemo\.com/);
  assert.match(html, /123 Demo Ln, Salem, OR 97301/);
  assert.match(html, /CCB #123456/);
});

test("field-safe packet excludes office-only notes and safety incidents", () => {
  const packet = deriveJobPrintPacket({
    packetMode: "field_safe",
    companyProfile: {
      logoInitials: "BC",
      printPacketHeaderColor: "#14532d",
      printPacketAccentColor: "#f59e0b",
      jobPacketCoverTitle: "Field Job Packet",
    },
    job: {
      id: "J-1",
      title: "Martinez Driveway",
      customer: "Martinez Residence",
      notes: "Office-only cleanup commitment.",
      fieldNotes: "Crew staged forms on site.",
      status: "in_progress",
    },
    changeOrderRequests: [{ id: "CO-1", jobId: "J-1", reason: "Extra apron width", status: "requested", scopeDescription: "Add 2 feet to the apron", officeNotes: "Price with premium broom finish." }],
    safetyIncidents: [{ id: "SI-1", jobId: "J-1", title: "Loose form stake", severity: "low", status: "resolved", description: "Stake reset before pour." }],
  });

  const html = buildPrintDocumentHtml(packet);
  assert.match(html, /Field-safe job packet/);
  assert.match(html, /Field Job Packet/);
  assert.match(html, /Ready for field use\./);
  assert.match(html, /Field-ready/);
  assert.match(html, /Closeout-ready/);
  assert.match(html, /Field scope changes are visible without office pricing notes\./);
  assert.match(html, /--packet-header: #14532d/);
  assert.match(html, /--packet-accent: #f59e0b/);
  assert.match(html, /Packet Review Summary/);
  assert.match(html, /Change Order Packet/);
  assert.doesNotMatch(html, /Office-only cleanup commitment\./);
  assert.match(html, /Crew staged forms on site\./);
  assert.doesNotMatch(html, /Price with premium broom finish\./);
  assert.doesNotMatch(html, /Loose form stake/);
});

test("proof closeout packet focuses on evidence and excludes private field-safe details", () => {
  const packet = deriveProofCloseoutPrintPacket({
    companyName: "Apex HQ Demo",
    companyProfile: {
      logoInitials: "AHD",
      printPacketHeaderColor: "#111827",
      printPacketHeaderTextColor: "#ffffff",
      printPacketAccentColor: "#14b8a6",
      proofCloseoutPacketCoverTitle: "Final Proof Packet",
      proofCloseoutPacketCoverKicker: "Closeout Evidence",
      proofCloseoutPacketTagline: "Photos, tickets, reports, and completion checks ready for review.\nfiles.example.test/private/cover",
      proofCloseoutPacketStatementTitle: "Ready for closeout review.",
      proofCloseoutPacketStatementBody: "Closeout photos, delivery tickets, final reports, and completion checklists are organized for approval.\nC:\\secret\\cover.pdf",
      proofCloseoutPacketReviewNote: "OFFICE_ONLY_SENTINEL margin target $12,000. See file:///C:/secret/closeout-margin.xlsx.",
      businessEmail: "closeout@apexhqdemo.com",
      businessPhone: "(503) 555-0100",
      serviceArea: "Portland metro",
    },
    printPacketFooter: "Apex HQ Demo field-safe closeout packet.",
    printPacketDisclaimer: "Internal closeout documentation. OFFICE_ONLY_SENTINEL Payment Terms: 50% deposit and legal terms apply. https://files.example.test/private/closeout.pdf",
    packetMode: "field_safe",
    job: {
      id: "J-100",
      title: "Keizer Patio Closeout",
      customer: "Keizer Residence",
      address: "789 Patio Ct",
      status: "completed",
      completedAt: "2026-05-27T19:30:00Z",
      scopeSummary: "Replace back patio and complete cleanup.\nOFFICE_ONLY_SENTINEL price floor is $12,000.\nfiles.example.test/private/scope",
      fieldNotes: "Crew captured final finish and cleanup photos. Closeout link https://files.example.test/private/field-closeout\n\\\\server\\share\\field-closeout.pdf",
      notes: "Office-only retainage note.",
      materialNotes: "6 yd3 broom finish mix. file:///C:/secret/materials.pdf\nPrivate note SOV backup.",
    },
    uploads: [
      { id: "UP-1", jobId: "J-100", fileName: "final-finish-file:///C:/secret/final.jpg", caption: "Final broom finish https://files.example.test/private/final.jpg", notes: "Owner approved finish.\nOFFICE_ONLY_SENTINEL margin photo note $12,000\ninvoice amount balance due pay application attorney fees contract terms profit labor cost private note SOV", url: "https://files.example.test/private/final.jpg" },
    ],
    dailyReports: [
      { id: "R-1", jobId: "J-100", reportDate: "2026-05-27", status: "reviewed", createdByName: "Demo Foreman", workPerformed: "Finished patio, sawcut joints, and cleaned site. Payment Terms: 50% deposit.", weather: "Clear www.private-weather.example/report", concretePoured: true, yardsPoured: 6 },
    ],
    deliveryTickets: [
      { id: "DT-1", jobId: "J-100", supplier: "Knife River https://files.example.test/private/ticket", ticketNumber: "T-90", truckNumber: "K-5 file:///C:/secret/ticket.jpg", yardsDelivered: 6, psi: 4000 },
    ],
    prePourChecklists: [
      { id: "PP-1", jobId: "J-100", status: "reviewed", items: [{ label: "Forms set", status: "checked" }, { label: "OFFICE_ONLY_SENTINEL margin form check", status: "checked" }] },
    ],
    postPourChecklists: [
      { id: "PO-1", jobId: "J-100", status: "completed", items: [{ label: "Final photos captured", status: "checked" }, { label: "Legal terms signature stored", status: "checked" }] },
    ],
    toolChecklists: [
      { id: "TC-1", jobId: "J-100", title: "Closeout tools", status: "submitted", items: [{ name: "Concrete saw", status: "on_site" }, { name: "Office-only rental cost", status: "on_site" }] },
    ],
    calculatorResults: [
      { id: "CALC-1", jobId: "J-100", calculatorType: "slab", summary: "Patio slab quantity.\nMargin target $12,000.", cubicYards: 5.6, cubicYardsWithWaste: 6.16 },
    ],
    changeOrderRequests: [
      { id: "CO-1", jobId: "J-100", reason: "Added landing", status: "approved", scopeDescription: "Add landing at back door. https://files.example.test/private/co", fieldNotes: "Owner marked layout. Retainage detail is office-only.", officeNotes: "Office-only invoice amount." },
    ],
  });

  const html = buildPrintDocumentHtml(packet);
  assert.equal(packet.title, "Proof / Closeout Packet");
  assert.equal(packet.packetMode, "field_safe");
  assert.match(html, /Closeout Evidence/);
  assert.match(html, /Final Proof Packet/);
  assert.match(html, /Ready for closeout review\./);
  assert.match(html, /Photos, tickets, reports, and completion checks ready for review\./);
  assert.match(html, /Field-safe closeout packet\. Restricted office details and private file links are excluded\./);
  assert.match(html, /Closeout Packet Summary/);
  assert.match(html, /Proof Photos \/ Uploads/);
  assert.match(html, /Delivery Ticket Backup/);
  assert.match(html, /Closeout Checklist Backup/);
  assert.match(html, /Closeout Change Orders/);
  assert.match(html, /Final broom finish/);
  assert.match(html, /Link tracked in Apex HQ\./);
  assert.match(html, /Knife River/);
  assert.match(html, /6 yd3 delivered/);
  assert.match(html, /Final photos captured/);
  assert.match(html, /Patio slab quantity/);
  assert.match(html, /Added landing/);
  assert.match(html, /--packet-header: #111827/);
  assert.match(html, /--packet-accent: #14b8a6/);
  assert.ok(html.indexOf('<section class="proposal-cover-page">') < html.indexOf('<header class="packet-header">'));
  assert.match(html, /Field-safe closeout documentation\. Restricted office details and private file links are excluded\./);
  assert.doesNotMatch(html, /Internal closeout documentation/);
  assert.doesNotMatch(html, /OFFICE_ONLY_SENTINEL/);
  assert.doesNotMatch(html, /margin target|margin photo note|price floor|Payment Terms|50% deposit|legal terms apply|Legal terms signature|Retainage detail|Office-only rental cost/i);
  assert.doesNotMatch(html, /\$12,000/);
  assert.doesNotMatch(html, /Office-only retainage note/);
  assert.doesNotMatch(html, /Office-only invoice amount/);
  assert.doesNotMatch(html, /invoice amount|balance due|pay application|attorney fees|contract terms|profit|labor cost|private note|SOV/i);
  assert.doesNotMatch(html, /files\.example\.test\/private/);
  assert.doesNotMatch(html, /private-weather\.example/);
  assert.doesNotMatch(html, /file:\/\//);
  assert.doesNotMatch(html, /C:\\secret|\\\\server\\share/);
  assert.doesNotMatch(html, /Â|Ã|â/);
  const emptyPacketHtml = buildPrintDocumentHtml(deriveProofCloseoutPrintPacket({
    companyName: "Apex HQ Demo",
    companyProfile: {
      proofCloseoutPacketCoverTitle: "OFFICE_ONLY_SENTINEL invoice amount",
    },
    printPacketFooter: "OFFICE_ONLY_SENTINEL files.example.test/private/no-job",
    printPacketDisclaimer: "Internal closeout documentation. C:\\secret\\no-job.pdf balance due.",
    packetMode: "field_safe",
    job: null,
  }));
  assert.match(emptyPacketHtml, /Field-safe closeout documentation\. Restricted office details and private file links are excluded\./);
  assert.doesNotMatch(emptyPacketHtml, /OFFICE_ONLY_SENTINEL|files\.example\.test\/private|C:\\secret|balance due|Internal closeout documentation/i);
});

test("change order packet focuses on scope change and excludes field-safe office details", () => {
  const fieldSafePacket = deriveChangeOrderPrintPacket({
    companyName: "Apex HQ Demo",
    companyProfile: {
      logoInitials: "AHD",
      printPacketHeaderColor: "#0f172a",
      printPacketHeaderTextColor: "#ffffff",
      printPacketAccentColor: "#f97316",
      changeOrderPacketCoverTitle: "Scope Change Packet",
      changeOrderPacketCoverKicker: "Change Order Review",
      changeOrderPacketTagline: "Requested scope, proof, and approval status in one clean packet.\nfiles.example.test/private/change-cover",
      changeOrderPacketStatementTitle: "Ready for change-order approval.",
      changeOrderPacketStatementBody: "Scope, field notes, job context, and proof uploads are organized for approval.\nC:\\secret\\change-order-pricing.pdf",
      changeOrderPacketReviewNote: "OFFICE_ONLY_SENTINEL margin target $12,000. See file:///C:/secret/change-order-margin.xlsx.",
      businessEmail: "changeorders@apexhqdemo.com",
      businessPhone: "(503) 555-0100",
      serviceArea: "Portland metro",
    },
    printPacketFooter: "Generated for customer approval. Internal margin backup at files.example.test/private/footer.",
    printPacketDisclaimer: "Internal billing terms, invoice amount, balance due, and attorney fees are office-only. file:///C:/secret/legal.pdf",
    packetMode: "field_safe",
    changeOrderRequest: {
      id: "CO-200",
      jobId: "J-200",
      customerName: "Yard Residence",
      requestedByName: "Demo Foreman",
      reviewedByName: "Office",
      reason: "Added back-door landing",
      scopeDescription: "Add a broom-finish landing at the back door with doweled tie-in.\nPrivate file backup: files.example.test/private/scope.pdf",
      fieldNotes: "Owner marked the landing corners in paint before pour.\nDeposit and final payment are office-only.",
      officeNotes: "Office-only pricing margin note with profit target, labor cost, invoice amount, balance due, SOV, pay application, contract terms, and attorney fees.",
      status: "under_review",
      createdAt: "2026-05-27T16:00:00Z",
      reviewedAt: "2026-05-27T18:00:00Z",
      updatedAt: "2026-05-27T18:15:00Z",
    },
    jobs: [
      { id: "J-200", title: "Yard Residence Patio", customer: "Yard Residence", address: "44 Garden Way", status: "active", siteContact: "Jamie Yard\n\\\\server\\share\\customer-approval.pdf" },
    ],
    uploads: [
      { id: "UP-200", jobId: "J-200", changeOrderId: "CO-200", fileName: "landing-layout.jpg", caption: "Painted landing layout", notes: "Corners marked by owner.\nInvoice amount, balance due, pay application, attorney fees, contract terms, profit, labor cost, private note, SOV.", uploadedAt: "2026-05-27T17:00:00Z", url: "https://files.example.test/private/landing.jpg" },
    ],
    dailyReports: [
      { id: "R-200", jobId: "J-200", reportDate: "2026-05-27", status: "submitted", createdByName: "Demo Foreman", workPerformed: "Measured requested landing and captured proof photo.\nC:\\secret\\daily-change.pdf", weather: "Clear www.private-weather.example/report" },
    ],
    deliveryTickets: [
      { id: "DT-200", jobId: "J-200", supplier: "Knife River files.example.test/private/ticket", ticketNumber: "T-200", truckNumber: "K-8 file:///C:/secret/ticket.pdf", yardsDelivered: 2, psi: 4000, slump: "4 in \\\\server\\share\\slump.pdf" },
    ],
  });

  const html = buildPrintDocumentHtml(fieldSafePacket);
  assert.equal(fieldSafePacket.title, "Change Order Packet");
  assert.equal(fieldSafePacket.packetMode, "field_safe");
  assert.match(html, /Change Order Review/);
  assert.match(html, /Scope Change Packet/);
  assert.match(html, /Ready for change-order approval\./);
  assert.match(html, /Requested scope, proof, and approval status in one clean packet\./);
  assert.match(html, /Field-safe change order packet\. Restricted office details and private file links are excluded\./);
  assert.match(html, /Change Order Summary/);
  assert.match(html, /Requested Scope Change/);
  assert.match(html, /Proof \/ Field Evidence/);
  assert.match(html, /Related Daily Reports/);
  assert.match(html, /Related Delivery Tickets/);
  assert.match(html, /Review \/ Approval Trail/);
  assert.match(html, /Added back-door landing/);
  assert.match(html, /Under Review/);
  assert.match(html, /Add a broom-finish landing at the back door/);
  assert.match(html, /Painted landing layout/);
  assert.match(html, /Knife River/);
  assert.match(html, /2 yd3 delivered/);
  assert.match(html, /Link tracked in Apex HQ/);
  assert.match(html, /File tracked in Apex HQ/);
  assert.match(html, /--packet-header: #0f172a/);
  assert.match(html, /--packet-accent: #f97316/);
  assert.doesNotMatch(html, /Office-only pricing margin note/);
  assert.doesNotMatch(html, /files\.example\.test\/private/);
  assert.doesNotMatch(html, /OFFICE_ONLY_SENTINEL|margin target|customer approval/i);
  assert.doesNotMatch(html, /invoice amount|balance due|pay application|attorney fees|contract terms|profit|labor cost|private note|SOV/i);
  assert.doesNotMatch(html, /billing terms|deposit|final payment|internal billing/i);
  assert.doesNotMatch(html, /\$\s?12,000/);
  assert.doesNotMatch(html, /private-weather\.example|file:\/\//);
  assert.doesNotMatch(html, /C:\\secret|\\\\server\\share/);
  assert.doesNotMatch(html, /Ã‚|Ãƒ|Ã¢/);

  const emptyPacketHtml = buildPrintDocumentHtml(deriveChangeOrderPrintPacket({
    companyName: "Apex HQ Demo",
    printPacketFooter: "OFFICE_ONLY_SENTINEL profit backup files.example.test/private/no-change",
    printPacketDisclaimer: "Internal billing terms. C:\\secret\\no-change.pdf balance due.",
    packetMode: "field_safe",
    changeOrderRequest: null,
  }));
  assert.match(emptyPacketHtml, /Field-safe change order documentation\. Restricted office details and private file links are excluded\./);
  assert.doesNotMatch(emptyPacketHtml, /OFFICE_ONLY_SENTINEL|files\.example\.test\/private|C:\\secret|balance due|Internal billing terms/i);

  const internalPacket = deriveChangeOrderPrintPacket({
    packetMode: "internal",
    changeOrderRequest: {
      id: "CO-201",
      jobId: "J-201",
      reason: "Added stairs",
      scopeDescription: "Add two stair treads.",
      fieldNotes: "Customer approved layout.",
      officeNotes: "Office-only pricing margin note.",
      status: "approved_for_pricing",
    },
    jobs: [{ id: "J-201", title: "Internal Job", status: "active" }],
  });
  assert.match(buildPrintDocumentHtml(internalPacket), /Office-only pricing margin note/);
});

test("estimate print packet includes customer-facing estimate details without internal notes", () => {
  const packet = deriveEstimatePrintPacket({
    companyName: "Apex HQ Demo",
    companyProfile: {
      logoInitials: "COD",
      logoImageUrl: "https://cdn.example.test/cod-logo.png",
      businessPhone: "(503) 555-0100",
      businessEmail: "office@apexhqdemo.com",
      website: "https://apexhqdemo.com",
      businessAddress: "123 Demo Ln, Salem, OR 97301",
      serviceArea: "Salem and Portland metro",
      licenseText: "CCB #123456 - Bonded and insured.",
    },
    printPacketFooter: "Generated by Apex HQ for job documentation, field reports, and closeout records.",
    printPacketDisclaimer: "Internal job documentation. Review all details before sharing outside the company.",
    estimate: {
      id: "EST-1",
      title: "Martinez Driveway Proposal",
      status: "sent",
      createdAt: "2026-04-26T16:30:00Z",
      scopeSummary: [
        "Scope of Work:",
        "Replace cracked driveway panels and pour a broom-finish apron.",
        "",
        "Inclusions:",
        "Demo, haul-off, forming, placement, and broom finish.",
        "",
        "Exclusions:",
        "Permit fees and utility relocation.",
        "",
        "Assumptions / Clarifications:",
        "Customer will provide clear access before the pour.",
      ].join("\n"),
      internalNotes: [
        "Office-only follow-up note.",
        "[Apex HQ GC Packet Lite]",
        JSON.stringify({
          proposalCoverNote: "Thank you for the opportunity to price this work.",
          proposalSummary: "GC-facing commercial concrete proposal summary.",
          qualifications: "Proposal is based on Addendum 01.",
          scheduleNotes: "Schedule will be coordinated with the GC.",
          addendaRfiReferences: "RFI 03 and Addendum 01 reviewed.",
          gcReviewNotes: "Office-only GC follow-up.",
          internalPacketNotes: "Internal packet assembly note.",
        }),
        "[/Apex HQ GC Packet Lite]",
        "[Apex HQ Estimate Backup]",
        JSON.stringify({
          takeoffRows: [{ item: "Driveway square footage", quantity: "640", unit: "SF", source: "Plan A1.1", estimatorNote: "Private takeoff note." }],
          referenceRows: [{ fileName: "Driveway marked-up photo.png", referenceType: "Photo", url: "https://files.example.test/private/driveway.png", source: "Plan A1.1", notes: "Private photo note." }],
          notes: "Private SOV backup",
        }),
        "[/Apex HQ Estimate Backup]",
        "[Apex HQ Sent Proposal History]",
        JSON.stringify([{ snapshotId: "snap-private", notes: "Private sent history" }]),
        "[/Apex HQ Sent Proposal History]",
      ].join("\n"),
      customerNotes: [
        "Customer Notes / Terms:",
        "Estimate is valid for 30 days.",
        "",
        "Payment Terms:",
        "50% deposit to schedule, balance due at completion.",
        "",
        "Warranty:",
        "Warranty terms are project-specific and exclude normal concrete movement.",
        "",
        "Acceptance / Next Steps:",
        "Signed approval and deposit release scheduling.",
        "",
        "Concrete Specifications:",
        "Thickness: 4 inch slab with thickened edge where noted.",
        "Finish: Broom finish with sawcut control joints.",
        "Concrete Strength: 4000 PSI.",
        "",
        "Pricing Options:",
        "- [selected] Standard driveway | Price: $12,500 | Deposit: $3,125 | Final Payment: $9,375 | Description: Broom finish driveway replacement. | Photo: https://cdn.example.test/options/standard.jpg | Caption: Standard broom finish sample.",
        "- [optional] Premium border | Price: $14,850 | Image: file:///C:/secret/premium.jpg | Caption: Decorative border sample.",
        "",
        "Option Photo Pages:",
        "- Cure photo | Photo: https://cdn.example.test/options/cure.jpg | Caption: Cure blanket reference. | Notes: Visual reference only.",
        "",
        "Residential Legal Notices:",
        "Owner is responsible for utility locates, irrigation lines, and required HOA approvals.",
        "",
        "Customer Approval:",
        "Selected standard driveway option approved by Jamie Martinez on 5/20/2026.",
        "",
        "Alternates:",
        "- [optional] Stamped border | Amount: $1,250.00 | Description: Add stamped border.",
        "- [accepted] Thicker driveway edge | Amount: $900.00",
        "- [excluded] Extra sawcutting | Amount: $300.00",
        "",
        "Optional Add-ons:",
        "- [selected] Sealer | Amount: $450.00",
      ].join("\n"),
      customer: { name: "Martinez Residence" },
      lead: { customer: "Martinez Residence", project: "Driveway replacement estimate" },
      items: [
        { description: "Demo and haul off", quantity: 1, unit: "LS", unitPrice: 1850 },
        { description: "Concrete placement", quantity: 9, unit: "yd", unitPrice: 215 },
      ],
      taxRate: 0,
      feesTotal: 125,
    },
    packetSettings: {
      presetId: "gcPrimeProposalPacket",
      customization: {
        themeId: "custom-brand",
        customThemeName: "Berlanda Concrete",
        headerColor: "#123abc",
        headerTextColor: "#fefefe",
        accentColor: "#00aa88",
        coverTitle: "Prime Bid Package",
        coverKicker: "Concrete Bid",
        tagline: "Built for GC review.",
        statementTitle: "Ready for award review.",
        statementBody: "Custom scope, alternates, and closeout expectations are organized for the GC team.",
        reviewNote: "Confirm addenda and inclusions before award.",
      },
    },
  });

  const html = buildPrintDocumentHtml(packet);
  assert.match(html, /Professional Packet/);
  assert.match(html, /GC \/ prime proposal packet/);
  assert.match(html, /Concrete Bid/);
  assert.match(html, /Prime Bid Package/);
  assert.match(html, /Built for GC review\./);
  assert.match(html, /Ready for award review\./);
  assert.match(html, /Custom scope, alternates, and closeout expectations are organized for the GC team\./);
  assert.match(html, /Confirm addenda and inclusions before award\./);
  assert.match(html, /--packet-accent: #00aa88/);
  assert.match(html, /--packet-header: #123abc/);
  assert.match(html, /--packet-header-text: #fefefe/);
  assert.doesNotMatch(html, /content:\s*"APEX"/);
  assert.match(html, /Why This Packet Is Ready/);
  assert.match(html, /Prepared For/);
  assert.match(html, /Project Summary/);
  assert.ok(html.indexOf('<section class="proposal-cover-page">') < html.indexOf('<header class="packet-header">'));
  assert.match(html, /Packet preset/);
  assert.match(html, /Packet Review Summary/);
  assert.match(html, /class="logo-image"/);
  assert.match(html, /https:\/\/cdn\.example\.test\/cod-logo\.png/);
  assert.doesNotMatch(html, /class="logo-mark">COD/);
  assert.match(html, /Martinez Driveway Proposal/);
  assert.match(html, /Driveway replacement estimate/);
  assert.match(html, /Scope of Work/);
  assert.match(html, /Inclusions/);
  assert.match(html, /Exclusions/);
  assert.match(html, /Assumptions \/ Clarifications/);
  assert.match(html, /Demo, haul-off, forming, placement, and broom finish\./);
  assert.match(html, /Permit fees and utility relocation\./);
  assert.match(html, /Proposal Cover Note/);
  assert.match(html, /Thank you for the opportunity to price this work\./);
  assert.match(html, /Proposal Summary/);
  assert.match(html, /GC-facing commercial concrete proposal summary\./);
  assert.match(html, /Qualifications/);
  assert.match(html, /Proposal is based on Addendum 01\./);
  assert.match(html, /Schedule Notes/);
  assert.match(html, /Schedule will be coordinated with the GC\./);
  assert.match(html, /Addenda \/ RFI References/);
  assert.match(html, /RFI 03 and Addendum 01 reviewed\./);
  assert.match(html, /Project Takeoff Summary/);
  assert.match(html, /Driveway square footage/);
  assert.match(html, /Project References/);
  assert.match(html, /Driveway marked-up photo\.png/);
  assert.match(html, /Demo and haul off/);
  assert.match(html, /Base Estimate Total/);
  assert.match(html, /Base estimate total/);
  assert.match(html, /Alternates/);
  assert.match(html, /Stamped border/);
  assert.match(html, /Thicker driveway edge/);
  assert.match(html, /Optional Add-ons/);
  assert.match(html, /Sealer/);
  assert.match(html, /Selected options total/);
  assert.match(html, /Total with selected options/);
  assert.match(html, /Estimate is valid for 30 days\./);
  assert.match(html, /Payment Terms/);
  assert.match(html, /50% deposit to schedule, balance due at completion\./);
  assert.match(html, /Warranty \/ Workmanship Notes/);
  assert.match(html, /Warranty terms are project-specific/);
  assert.match(html, /Acceptance \/ Next Steps/);
  assert.match(html, /Signed approval and deposit release scheduling\./);
  assert.match(html, /Project Specifications/);
  assert.match(html, /Broom finish with sawcut control joints\./);
  assert.match(html, /Customer Pricing Options/);
  assert.match(html, /Pricing choices/);
  assert.match(html, /Standard driveway/);
  assert.match(html, /Down payment \$3,125\.00/);
  assert.match(html, /Final payment \$9,375\.00/);
  assert.match(html, /Option \/ Finish References/);
  assert.match(html, /class="record-image"/);
  assert.match(html, /Cure blanket reference\./);
  assert.doesNotMatch(html, /Residential Legal Notices/);
  assert.doesNotMatch(html, /Owner is responsible for utility locates/);
  assert.doesNotMatch(html, /Customer Approval Record/);
  assert.doesNotMatch(html, /Selected standard driveway option approved/);
  assert.doesNotMatch(html, /Photo: https/);
  assert.doesNotMatch(html, /file:\/\/\/C:\/secret/);
  assert.doesNotMatch(html, /class="logo-mark">COD/);
  assert.match(html, /\(503\) 555-0100/);
  assert.match(html, /office@apexhqdemo\.com/);
  assert.match(html, /https:\/\/apexhqdemo\.com/);
  assert.match(html, /123 Demo Ln, Salem, OR 97301/);
  assert.match(html, /Salem and Portland metro/);
  assert.match(html, /CCB #123456 - Bonded and insured\./);
  assert.match(html, /Generated by Apex HQ for job documentation, field reports, and closeout records\./);
  assert.match(html, /Internal job documentation\. Review all details before sharing outside the company\./);
  assert.doesNotMatch(html, /Office-only follow-up note\./);
  assert.doesNotMatch(html, /Office-only GC follow-up/);
  assert.doesNotMatch(html, /Internal packet assembly note/);
  assert.doesNotMatch(html, /Private SOV backup/);
  assert.doesNotMatch(html, /Private takeoff note/);
  assert.doesNotMatch(html, /Private photo note/);
  assert.doesNotMatch(html, /files\.example\.test\/private/);
  assert.doesNotMatch(html, /Private sent history/);
  assert.doesNotMatch(html, /Apex HQ GC Packet Lite/);
  assert.doesNotMatch(html, /Â|â/);
  assert.match(html, /@page \{ margin: 0\.5in; \}/);
  assert.match(html, /white-space: pre-line/);
  assert.match(html, /page-break-inside: avoid/);
  assert.match(html, /page-break-after: avoid/);
});

test("estimate print packet uses saved company packet branding when no packet override is selected", () => {
  const packet = deriveEstimatePrintPacket({
    companyName: "Pacific Flatwork",
    companyProfile: {
      logoInitials: "PF",
      printPacketHeaderColor: "#112233",
      printPacketHeaderTextColor: "#f8fafc",
      printPacketAccentColor: "#00aa88",
      printPacketAccentDarkColor: "#005544",
      printPacketAccentSoftColor: "#e6fffa",
    },
    estimate: {
      title: "Patio Proposal",
      scopeSummary: "Scope of Work:\nPour backyard patio.",
      customerNotes: "Payment Terms:\n50% deposit.",
      customer: { name: "Yard Residence" },
      lead: { customer: "Yard Residence", project: "Backyard patio" },
      items: [{ description: "Patio concrete", quantity: 1, unit: "LS", unitPrice: 4500 }],
    },
  });

  const html = buildPrintDocumentHtml(packet);
  assert.match(html, /--packet-header: #112233/);
  assert.match(html, /--packet-header-text: #f8fafc/);
  assert.match(html, /--packet-accent: #00aa88/);
  assert.match(html, /--packet-accent-dark: #005544/);
  assert.match(html, /--packet-accent-soft: #e6fffa/);
});

test("estimate foreman handoff packet includes field scope and quantities without pricing or office-only notes", () => {
  const packet = deriveEstimateForemanHandoffPacket({
    companyName: "Builders Concrete Co.",
    companyProfile: {
      logoInitials: "BCC",
      logoImageUrl: "https://cdn.example.test/bcc-logo.png",
      businessPhone: "(503) 555-0188",
      businessEmail: "office@buildersconcrete.test",
      primaryTrade: "concrete",
    },
    printPacketFooter: "Field handoff footer.",
    printPacketDisclaimer: "Review before field use.",
    estimate: {
      id: "EST-FIELD-1",
      title: "Salem Warehouse Slab",
      status: "approved",
      createdAt: "2026-05-15T15:30:00Z",
      scopeSummary: [
        "Scope of Work:",
        "Demo old concrete, prep base rock, pour 500 SF 4-inch broom finish slab, sawcut edges, cleanup. Plan link https://plans.example.test/private/slab.",
        "Office-only margin: 42%. Price floor is $9,999.",
        "Payment Terms:",
        "50% deposit and legal terms apply.",
        "See file:///C:/secret/scope.pdf before crew handoff.",
        "",
        "Inclusions:",
        "Base rock, forms, concrete placement, broom finish, and cleanup.",
        "",
        "Exclusions:",
        "Permits, engineering, unsuitable soils, and winter protection.",
        "",
        "Assumptions / Clarifications:",
        "Truck access remains available during placement.",
      ].join("\n"),
      customerNotes: [
        "Customer Notes / Terms:",
        "Proposal is valid for 30 days.",
        "",
        "Alternates:",
        "- [selected] Winter protection | Amount: $1,800.00",
      ].join("\n"),
      customer: { name: "ABC Builders" },
      lead: { customer: "ABC Builders", project: "Salem warehouse slab" },
      items: [
        { description: "Demo and haul off", quantity: 1, unit: "LS", unitPrice: 2500 },
        { description: "4-inch broom finish slab - field note $99.00 https://field.example.test/private", quantity: 500, unit: "SF", unitPrice: 14.5 },
      ],
      internalNotes: [
        "Office-only pricing note. Margin target 22%. file:///C:/secret/crew-margin.xlsx",
        "[Apex HQ GC Packet Lite]",
        JSON.stringify({
          scheduleNotes: "Coordinate pour window with superintendent.",
          addendaRfiReferences: "Bluebeam takeoff from S2.1.",
          gcReviewNotes: "Internal GC follow-up note.",
          internalPacketNotes: "Private packet assembly note.",
        }),
        "[/Apex HQ GC Packet Lite]",
        "[Apex HQ Estimate Backup]",
        JSON.stringify({
          sovRows: [{ section: "Concrete", description: "Slab placement", quantity: "500", unit: "SF", amount: "$7,250", notes: "Office SOV amount." }],
          takeoffRows: [
            { item: "Warehouse slab", quantity: "500", unit: "SF", source: "S2.1 https://takeoff.example.test/private", estimatorNote: "Verify edge thickening allowance." },
            { item: "Office-only studio yield", quantity: "10", unit: "CY", source: "Apex Takeoff Studio office-only / S2.1", estimatorNote: "Private yield and margin note." },
          ],
          referenceRows: [{ fileName: "Bluebeam slab takeoff.png", referenceType: "Takeoff screenshot", url: "https://files.example.test/private/slab.png", source: "S2.1 file:///C:/secret/takeoff.png", notes: "Private marked-up file." }],
          takeoffStudio: {
            sheets: [
              { id: "s-old", name: "S2.1", revision: "Rev A", status: "superseded" },
              { id: "s-new", name: "S2.1", revision: "Rev B", status: "active" },
            ],
            items: [
              { id: "field-safe-slab", label: "Field-safe revised slab", sheetId: "s-new", sheetName: "S2.1", revision: "Rev B", measurementType: "area", quantity: 540, unit: "SF", reviewStatus: "reviewed", fieldVisible: true, customerVisible: true, revisionStatus: "revised" },
              { id: "office-only-slab", label: "Office-only studio yield", sheetId: "s-new", sheetName: "S2.1", revision: "Rev B", measurementType: "volume", quantity: 10, unit: "CY", reviewStatus: "reviewed", fieldVisible: false, customerVisible: false, estimatorNote: "Private yield and margin note." },
            ],
          },
          notes: "Private backup note.",
        }),
        "[/Apex HQ Estimate Backup]",
      ].join("\n"),
      taxRate: 0,
      feesTotal: 125,
    },
    packetSettings: {
      customization: {
        themeId: "custom-brand",
        customThemeName: "Foreman Handoff",
        headerColor: "#14532d",
        headerTextColor: "#ffffff",
        accentColor: "#f59e0b",
        coverTitle: "Crew Handoff",
        coverKicker: "Field Handoff Packet",
        tagline: "Scope, quantities, references, and proof requirements for the crew.",
        statementTitle: "Ready for field handoff.",
        statementBody: "Field-safe scope, quantities, references, proof photo requirements, and change-order watchouts are organized for the foreman before work begins.",
        reviewNote: "No customer pricing, totals, cost detail, or office-only backup in this packet.",
      },
    },
  });

  const html = buildPrintDocumentHtml(packet);
  assert.equal(packet.packetMode, "field_safe");
  assert.match(html, /Foreman Handoff Packet/);
  assert.match(html, /Field Handoff Packet/);
  assert.match(html, /Crew Handoff/);
  assert.match(html, /Ready for field handoff\./);
  assert.match(html, /No customer pricing, totals, cost detail, or office-only backup in this packet\./);
  assert.match(html, /Scope, quantities, references/);
  assert.match(html, /Pre-mobilization review/);
  assert.match(html, /Daily setup/);
  assert.match(html, /Quantity control/);
  assert.match(html, /Proof trail/);
  assert.match(html, /Change-order watch/);
  assert.match(html, /--packet-header: #14532d/);
  assert.match(html, /--packet-accent: #f59e0b/);
  assert.match(html, /Handoff Packet Summary/);
  assert.match(html, /ABC Builders/);
  assert.match(html, /Salem warehouse slab/);
  assert.match(html, /Demo old concrete/);
  assert.match(html, /Permits, engineering, unsuitable soils, and winter protection\./);
  assert.match(html, /Coordinate pour window with superintendent\./);
  assert.match(html, /Field Quantities/);
  assert.match(html, /4-inch broom finish slab/);
  assert.match(html, /Qty 500/);
  assert.match(html, /SF/);
  assert.match(html, /Takeoff \/ Reference Attachments/);
  assert.match(html, /Field-safe revised slab/);
  assert.match(html, /Source S2\.1 \/ Rev B/);
  assert.match(html, /Bluebeam slab takeoff\.png/);
  assert.match(html, /Source S2\.1/);
  assert.match(html, /Link tracked in Apex HQ\./);
  assert.match(html, /Amount hidden from field/);
  assert.match(html, /Concrete Field Handoff Checklist/);
  assert.match(html, /Confirm layout and elevations/);
  assert.match(html, /Concrete Proof Photo Checklist/);
  assert.match(html, /Forms\/rebar/);
  assert.match(html, /Concrete Change-Order Watchouts/);
  assert.match(html, /Unsuitable subgrade/);
  assert.match(html, /class="logo-image"/);
  assert.doesNotMatch(html, /Unit price/);
  assert.doesNotMatch(html, /Line total/);
  assert.doesNotMatch(html, /Base Estimate Total/);
  assert.doesNotMatch(html, /Selected options total/);
  assert.doesNotMatch(html, /Review pricing options/);
  assert.doesNotMatch(html, /\$7,250/);
  assert.doesNotMatch(html, /\$9,999/);
  assert.doesNotMatch(html, /\$1,800/);
  assert.doesNotMatch(html, /Customer Notes \/ Terms/);
  assert.doesNotMatch(html, /Proposal is valid for 30 days/);
  assert.doesNotMatch(html, /Office-only margin/);
  assert.doesNotMatch(html, /margin: 42%/);
  assert.doesNotMatch(html, /Price floor/);
  assert.doesNotMatch(html, /Payment Terms/);
  assert.doesNotMatch(html, /50% deposit/);
  assert.doesNotMatch(html, /legal terms/);
  assert.doesNotMatch(html, /Office-only pricing note/);
  assert.doesNotMatch(html, /Margin target/);
  assert.doesNotMatch(html, /crew-margin\.xlsx/);
  assert.doesNotMatch(html, /Internal GC follow-up note/);
  assert.doesNotMatch(html, /Private packet assembly note/);
  assert.doesNotMatch(html, /Private backup note/);
  assert.doesNotMatch(html, /Office SOV amount/);
  assert.doesNotMatch(html, /Office-only studio yield/);
  assert.doesNotMatch(html, /Verify edge thickening allowance/);
  assert.doesNotMatch(html, /files\.example\.test\/private/);
  assert.doesNotMatch(html, /plans\.example\.test\/private/);
  assert.doesNotMatch(html, /field\.example\.test\/private/);
  assert.doesNotMatch(html, /takeoff\.example\.test\/private/);
  assert.doesNotMatch(html, /file:\/\//);
  assert.doesNotMatch(html, /\bwww\./);
  assert.doesNotMatch(html, /\$99\.00/);
  assert.doesNotMatch(html, /Private marked-up file/);
});

test("estimate foreman handoff packet default cover reads like a polished crew packet", () => {
  const packet = deriveEstimateForemanHandoffPacket({
    companyName: "Builders Concrete Co.",
    companyProfile: {
      logoInitials: "BCC",
      businessPhone: "(503) 555-0188",
      businessEmail: "office@buildersconcrete.test",
      primaryTrade: "concrete",
    },
    estimate: {
      id: "EST-FIELD-DEFAULT",
      title: "Retail Apron Replacement",
      status: "approved",
      createdAt: "2026-05-16T15:30:00Z",
      scopeSummary: "Scope of Work:\nSawcut, remove, prep, and pour concrete apron.\n\nExclusions:\nPermits and unsuitable soils.",
      customerNotes: "Payment Terms:\n50% deposit before mobilization.",
      customer: { name: "Retail Owner" },
      lead: { customer: "Retail Owner", project: "Apron replacement" },
      items: [{ description: "Concrete apron", quantity: 220, unit: "SF", unitPrice: 18 }],
      internalNotes: "Office-only pricing note. Margin $1,200. https://private.example.test/margin",
    },
  });

  const html = buildPrintDocumentHtml(packet);
  assert.match(html, /Crew Field Packet/);
  assert.match(html, /Foreman Handoff Packet/);
  assert.match(html, /Ready for crew review\./);
  assert.match(html, /Scope, quantities, references, proof photos, and change-order triggers/);
  assert.match(html, /Field-safe packet\. Pricing, totals, margins, customer payment terms, internal notes, and private file links are excluded\./);
  assert.match(html, /Scope, quantities, references/);
  assert.match(html, /Pre-mobilization review/);
  assert.match(html, /No pricing, margin, or office backup/);
  assert.match(html, /Daily setup/);
  assert.match(html, /Quantity control/);
  assert.match(html, /Proof trail/);
  assert.match(html, /Concrete apron/);
  assert.match(html, /Qty 220/);
  assert.doesNotMatch(html, /Unit price/);
  assert.doesNotMatch(html, /Line total/);
  assert.doesNotMatch(html, /Base Estimate Total/);
  assert.doesNotMatch(html, /Payment Terms/);
  assert.doesNotMatch(html, /50% deposit/);
  assert.doesNotMatch(html, /Office-only pricing note/);
  assert.doesNotMatch(html, /Margin \$1,200/);
  assert.doesNotMatch(html, /private\.example\.test/);
});

test("estimate print packet uses branded logo fallback safely", () => {
  const packet = deriveEstimatePrintPacket({
    companyName: "Builders Concrete Co.",
    companyProfile: {
      logoInitials: "BCC",
      logoImageUrl: "javascript:alert(1)",
      businessPhone: "(503) 555-0188",
      businessEmail: "office@buildersconcrete.test",
    },
    estimate: {
      id: "EST-BRAND-1",
      title: "Salem Warehouse Slab",
      status: "draft",
      customer: { name: "ABC Builders" },
      lead: { customer: "ABC Builders", project: "Warehouse slab" },
      scopeSummary: "Scope of Work:\nPour 500 SF warehouse slab.",
      items: [{ description: "Concrete slab", quantity: 500, unit: "SF", unitPrice: 12 }],
    },
  });

  const html = buildPrintDocumentHtml(packet);
  assert.doesNotMatch(html, /javascript:alert/);
  assert.doesNotMatch(html, /class="logo-image"/);
  assert.match(html, /class="logo-mark">BCC/);
  assert.match(html, /Builders Concrete Co\./);
  assert.match(html, /office@buildersconcrete\.test/);
  assert.match(html, /Salem Warehouse Slab/);
});

test("estimate print packet renders proposal text with readable summary bands and bullets", () => {
  const packet = deriveEstimatePrintPacket({
    companyName: "Apex HQ Demo",
    companyProfile: {
      businessPhone: "(503) 555-0100",
      businessEmail: "office@apexhqdemo.com",
    },
    estimate: {
      title: "Keizer Patio Project",
      status: "draft",
      createdAt: "2026-04-26T16:30:00Z",
      scopeSummary: [
        "Scope of Work:",
        "Replace cracked patio concrete and refresh the edge detail.",
        "",
        "Inclusions:",
        "- Demo and haul-off",
        "- Base rock and prep",
        "- Concrete placement",
        "- Broom finish and cleanup",
        "",
        "Assumptions / Clarifications:",
        "- Existing access remains open",
        "- Final color selection is confirmed before scheduling",
      ].join("\n"),
      customerNotes: [
        "Customer Notes / Terms:",
        "Proposal is valid for 30 days.",
        "",
        "Schedule Notes:",
        "Work is planned for the next available weather window.",
      ].join("\n"),
      customer: { name: "Keizer Residence" },
      lead: { customer: "Keizer Residence", project: "Patio replacement" },
      items: [{ description: "Concrete placement", quantity: 1, unit: "LS", unitPrice: 7250 }],
    },
  });

  const html = buildPrintDocumentHtml(packet);
  assert.match(html, /class="summary-band"/);
  assert.match(html, /class="text-flow"/);
  assert.match(html, /class="bullet-list"/);
  assert.match(html, /Demo and haul-off/);
  assert.match(html, /Base rock and prep/);
  assert.match(html, /Proposal is valid for 30 days\./);
  assert.match(html, /Schedule Notes/);
});

test("estimate print packet keeps old plain estimates readable", () => {
  const packet = deriveEstimatePrintPacket({
    estimate: {
      id: "EST-LEGACY",
      title: "Plain Estimate",
      scopeSummary: "Plain one-paragraph scope.",
      customerNotes: "Plain customer terms.",
      items: [],
    },
  });

  const html = buildPrintDocumentHtml(packet);
  assert.match(html, /Scope of Work/);
  assert.match(html, /Plain one-paragraph scope\./);
  assert.match(html, /Customer Notes \/ Terms/);
  assert.match(html, /Plain customer terms\./);
  assert.doesNotMatch(html, /Alternates/);
  assert.doesNotMatch(html, /Total with selected options/);
});

test("estimate print packet presets control included customer-facing sections", () => {
  const estimate = {
    id: "EST-PRESET",
    title: "Commercial Proposal",
    scopeSummary: [
      "Scope of Work:",
      "Place site concrete.",
      "",
      "Inclusions:",
      "Forms and finish.",
      "",
      "Exclusions:",
      "Permits.",
      "",
      "Assumptions / Clarifications:",
      "Clear access.",
    ].join("\n"),
    internalNotes: [
      "[Apex HQ GC Packet Lite]",
      JSON.stringify({
        proposalCoverNote: "GC cover note.",
        proposalSummary: "GC proposal summary.",
        qualifications: "Qualification note.",
        scheduleNotes: "Schedule note.",
        addendaRfiReferences: "Addendum 01.",
        gcReviewNotes: "Office-only GC note.",
      }),
      "[/Apex HQ GC Packet Lite]",
    ].join("\n"),
    customerNotes: [
      "Customer Notes / Terms:",
      "Valid for 30 days.",
      "",
      "Alternates:",
      "- [accepted] Thicker edge | Amount: $500.00",
    ].join("\n"),
    items: [{ description: "Concrete placement", quantity: 1, unit: "LS", unitPrice: 10000 }],
  };

  const basicHtml = buildPrintDocumentHtml(deriveEstimatePrintPacket({
    estimate,
    packetSettings: { presetId: "basicEstimate" },
  }));
  assert.match(basicHtml, /Scope of Work/);
  assert.match(basicHtml, /Alternates/);
  assert.doesNotMatch(basicHtml, /GC cover note/);
  assert.doesNotMatch(basicHtml, /Qualification note/);
  assert.doesNotMatch(basicHtml, /Office-only GC note/);

  const estimateSheetHtml = buildPrintDocumentHtml(deriveEstimatePrintPacket({
    estimate,
    packetSettings: { presetId: "polishedEstimateSheet" },
  }));
  assert.match(estimateSheetHtml, /Estimate Sheet/);
  assert.match(estimateSheetHtml, /Why This Estimate Is Ready/);
  assert.match(estimateSheetHtml, /Apex HQ estimate sheet\./);
  assert.doesNotMatch(estimateSheetHtml, /Concrete Proposal/);
  assert.doesNotMatch(estimateSheetHtml, /Apex HQ proposal packet\./);
  assert.doesNotMatch(estimateSheetHtml, /Why This Packet Is Ready/);

  const residentialHtml = buildPrintDocumentHtml(deriveEstimatePrintPacket({
    estimate,
    packetSettings: { presetId: "residentialProposalPacket" },
  }));
  assert.match(residentialHtml, /Residential Proposal/);
  assert.match(residentialHtml, /Ready for homeowner review\./);
  assert.match(residentialHtml, /homeowner-ready proposal/);
  assert.match(residentialHtml, /Home scope/);
  assert.doesNotMatch(residentialHtml, /contractor proposal packet/);

  const gcPacketHtml = buildPrintDocumentHtml(deriveEstimatePrintPacket({
    estimate,
    packetSettings: { presetId: "gcBidPacket" },
  }));
  assert.match(gcPacketHtml, /Proposal Cover Note/);
  assert.match(gcPacketHtml, /GC cover note/);
  assert.match(gcPacketHtml, /Addenda \/ RFI References/);
  assert.match(gcPacketHtml, /Addendum 01\./);
  assert.doesNotMatch(gcPacketHtml, /Office-only GC note/);

  const gcPrimeHtml = buildPrintDocumentHtml(deriveEstimatePrintPacket({
    estimate,
    packetSettings: { presetId: "gcPrimeProposalPacket" },
  }));
  assert.match(gcPrimeHtml, /Bid Package/);
  assert.match(gcPrimeHtml, /Ready for award review\./);
  assert.match(gcPrimeHtml, /GC-ready bid package/);
  assert.match(gcPrimeHtml, /Bid scope/);
  assert.match(gcPrimeHtml, /Addenda \/ RFI/);
  assert.doesNotMatch(gcPrimeHtml, /contractor proposal packet/);
});

test("residential proposal packet supports reusable custom branding and copy", () => {
  const html = buildPrintDocumentHtml(deriveEstimatePrintPacket({
    companyName: "Berlanda Concrete",
    companyProfile: {
      logoInitials: "BC",
      businessPhone: "(503) 555-0111",
      businessEmail: "office@berlanda.test",
      accentColor: "#c2410c",
    },
    estimate: {
      title: "Patio Replacement Proposal",
      createdAt: "2026-05-27T12:00:00.000Z",
      scopeSummary: [
        "Scope of Work:",
        "Remove existing patio, prep base, pour broom-finish concrete, and clean work area.",
        "",
        "Inclusions:",
        "Demo, forming, concrete, broom finish, sawcuts, and cleanup.",
        "",
        "Exclusions:",
        "Permits and underground utility repairs.",
      ].join("\n"),
      customerNotes: [
        "Customer Notes / Terms:",
        "Deposit due at scheduling. Balance due at completion.",
        "",
        "Warranty / Workmanship Notes:",
        "Workmanship warranty applies to completed concrete placement.",
        "",
        "Acceptance / Next Steps:",
        "Signed approval and deposit release scheduling.",
        "",
        "Customer Approval:",
        "Selected patio replacement proposal approved by homeowner.",
      ].join("\n"),
      customer: { name: "Keizer Residence" },
      lead: { customer: "Keizer Residence", project: "Back patio" },
      items: [{ description: "Patio replacement", quantity: 1, unit: "LS", unitPrice: 8400 }],
    },
    packetSettings: {
      presetId: "residentialProposalPacket",
      customization: {
        themeId: "custom-brand",
        customThemeName: "Berlanda Residential",
        headerColor: "#102a43",
        headerTextColor: "#ffffff",
        accentColor: "#c2410c",
        coverTitle: "Residential Finish Package",
        coverKicker: "Residential Proposal",
        tagline: "Clear scope. Clean finish. Built for your home.",
        statementTitle: "Ready for homeowner review.",
        statementBody: "Options, terms, warranty notes, and approval details are organized for a confident homeowner decision.",
        reviewNote: "Confirm finish, schedule, and payment terms before approval.",
      },
    },
  }));

  assert.match(html, /Residential Proposal/);
  assert.match(html, /Residential Finish Package/);
  assert.match(html, /Clear scope\. Clean finish\. Built for your home\./);
  assert.match(html, /Ready for homeowner review\./);
  assert.match(html, /Confirm finish, schedule, and payment terms before approval\./);
  assert.match(html, /--packet-header: #102a43/);
  assert.match(html, /--packet-accent: #c2410c/);
  assert.match(html, /Customer Approval Record/);
  assert.match(html, /Warranty \/ Workmanship Notes/);
  assert.doesNotMatch(html, /Office-only/);
  assert.doesNotMatch(html, /Private takeoff note|Internal packet assembly note/);
});

test("commercial subcontractor packet supports custom subcontractor branding and copy", () => {
  const html = buildPrintDocumentHtml(deriveEstimatePrintPacket({
    companyName: "Pacific Flatwork Co.",
    companyProfile: {
      logoInitials: "PF",
      businessPhone: "(503) 555-0144",
      businessEmail: "bids@pacificflatwork.test",
      serviceArea: "Willamette Valley commercial projects",
    },
    estimate: {
      title: "Tenant Improvement Slab Bid",
      createdAt: "2026-05-27T12:00:00.000Z",
      scopeSummary: [
        "Scope of Work:",
        "Place interior slab patch, dowel edges, finish to match adjacent slab, and coordinate pour access with GC.",
        "",
        "Inclusions:",
        "Layout coordination, forming, dowels, ready-mix placement, finishing, curing, and cleanup.",
        "",
        "Exclusions:",
        "Engineering, permits, demo by others, and after-hours premium labor.",
        "",
        "Assumptions / Clarifications:",
        "Bid assumes clear access, one mobilization, and GC-provided waste area.",
      ].join("\n"),
      customerNotes: [
        "Qualifications:",
        "Proposal is based on bid drawings, Addendum 02, and normal working-hour access.",
        "",
        "Schedule Notes:",
        "Crew can mobilize within ten business days after written award and submittal approval.",
        "",
        "Payment Terms:",
        "Progress billing by approved schedule of values. Retainage per subcontract terms.",
        "",
        "Acceptance / Next Steps:",
        "Written subcontract award and approved start date release procurement.",
        "",
        "Residential Legal Notices:",
        "Owner is responsible for utility locates and HOA approvals.",
        "",
        "Customer Approval:",
        "Homeowner approval record should not print in commercial subcontractor packets.",
      ].join("\n"),
      internalNotes: [
        "Office-only commercial margin note.",
        "[Apex HQ GC Packet Lite]",
        JSON.stringify({
          proposalSummary: "Commercial subcontractor summary.",
          qualifications: "Customer-safe commercial qualification.",
          gcReviewNotes: "Office-only GC strategy.",
          internalPacketNotes: "Internal packet assembly note.",
        }),
        "[/Apex HQ GC Packet Lite]",
        "[Apex HQ Estimate Backup]",
        JSON.stringify({
          referenceRows: [{ fileName: "Private commercial takeoff.png", url: "https://files.example.test/private/commercial.png", notes: "Private takeoff note" }],
          notes: "Private SOV backup",
        }),
        "[/Apex HQ Estimate Backup]",
      ].join("\n"),
      customer: { name: "North Valley GC" },
      lead: { customer: "North Valley GC", project: "Retail tenant improvement" },
      items: [{ description: "Interior slab patch", quantity: 1, unit: "LS", unitPrice: 18600 }],
    },
    packetSettings: {
      presetId: "commercialSubcontractorPacket",
      customization: {
        themeId: "custom-brand",
        customThemeName: "Pacific Flatwork Commercial",
        headerColor: "#172554",
        headerTextColor: "#ffffff",
        accentColor: "#0f766e",
        coverTitle: "Commercial Sub Bid",
        coverKicker: "Subcontractor Proposal",
        tagline: "Scope boundaries, coordination notes, and billing terms ready for review.",
        statementTitle: "Ready for subcontract review.",
        statementBody: "Qualifications, schedule coordination, alternates, exclusions, and billing terms are organized for the project team.",
        reviewNote: "Confirm scope limits, addenda, access, and billing terms before award.",
      },
    },
  }));

  assert.match(html, /Subcontractor Proposal/);
  assert.match(html, /Commercial Sub Bid/);
  assert.match(html, /Ready for subcontract review\./);
  assert.match(html, /Scope boundaries, coordination notes, and billing terms ready for review\./);
  assert.match(html, /Qualifications/);
  assert.match(html, /Proposal is based on bid drawings, Addendum 02/);
  assert.match(html, /Schedule Notes/);
  assert.match(html, /Retainage per subcontract terms/);
  assert.match(html, /--packet-header: #172554/);
  assert.match(html, /--packet-accent: #0f766e/);
  assert.doesNotMatch(html, /Residential Legal Notices/);
  assert.doesNotMatch(html, /Customer Approval Record|Homeowner approval record|Owner is responsible for utility locates/);
  assert.doesNotMatch(html, /Office-only|Internal packet assembly note|Private takeoff note|Private SOV backup/);
  assert.doesNotMatch(html, /files\.example\.test|Apex HQ Estimate Backup|Apex HQ GC Packet Lite/);
});

test("commercial subcontractor packet uses polished subcontractor defaults", () => {
  const html = buildPrintDocumentHtml(deriveEstimatePrintPacket({
    companyName: "Pacific Flatwork Co.",
    companyProfile: {
      logoInitials: "PF",
      businessPhone: "(503) 555-0144",
      businessEmail: "bids@pacificflatwork.test",
      serviceArea: "Willamette Valley commercial projects",
    },
    estimate: {
      title: "Tenant Improvement Slab Bid",
      createdAt: "2026-05-27T12:00:00.000Z",
      scopeSummary: [
        "Scope of Work:",
        "Place interior slab patch, dowel edges, finish to match adjacent slab, and coordinate pour access with GC.",
        "",
        "Inclusions:",
        "Layout coordination, forming, dowels, ready-mix placement, finishing, curing, and cleanup.",
        "",
        "Exclusions:",
        "Engineering, permits, demo by others, and after-hours premium labor.",
        "",
        "Assumptions / Clarifications:",
        "Bid assumes clear access, one mobilization, and GC-provided waste area.",
      ].join("\n"),
      customerNotes: [
        "Qualifications:",
        "Proposal is based on bid drawings, Addendum 02, and normal working-hour access.",
        "",
        "Schedule Notes:",
        "Crew can mobilize within ten business days after written award and submittal approval.",
        "",
        "Payment Terms:",
        "Progress billing by approved schedule of values. Retainage per subcontract terms.",
        "",
        "Acceptance / Next Steps:",
        "Written subcontract award and approved start date release procurement.",
        "",
        "Residential Legal Notices:",
        "Owner is responsible for utility locates and HOA approvals.",
        "",
        "Customer Approval:",
        "Homeowner approval record should not print in commercial subcontractor packets.",
      ].join("\n"),
      internalNotes: [
        "Office-only commercial margin note.",
        "[Apex HQ GC Packet Lite]",
        JSON.stringify({
          proposalSummary: "Commercial subcontractor summary.",
          qualifications: "Customer-safe commercial qualification.",
          gcReviewNotes: "Office-only GC strategy.",
          internalPacketNotes: "Internal packet assembly note.",
        }),
        "[/Apex HQ GC Packet Lite]",
        "[Apex HQ Estimate Backup]",
        JSON.stringify({
          referenceRows: [{ fileName: "Private commercial takeoff.png", url: "https://files.example.test/private/commercial.png", notes: "Private takeoff note" }],
          notes: "Private SOV backup",
        }),
        "[/Apex HQ Estimate Backup]",
      ].join("\n"),
      customer: { name: "North Valley GC" },
      lead: { customer: "North Valley GC", project: "Retail tenant improvement" },
      items: [{ description: "Interior slab patch", quantity: 1, unit: "LS", unitPrice: 18600 }],
    },
    packetSettings: {
      presetId: "commercialSubcontractorPacket",
    },
  }));

  assert.match(html, /Subcontractor Proposal/);
  assert.match(html, /Commercial Sub Bid/);
  assert.match(html, /Scope boundaries, coordination notes, and billing terms ready for review\./);
  assert.match(html, /Ready for subcontract review\./);
  assert.match(html, /Qualifications, schedule coordination, alternates, exclusions, and billing terms are organized for the project team\./);
  assert.match(html, /Confirm scope limits, addenda, access, and billing terms before award\./);
  assert.match(html, /Scope limits/);
  assert.match(html, /Billing terms/);
  assert.match(html, /Retainage per subcontract terms/);
  assert.doesNotMatch(html, /A contractor proposal packet/i);
  assert.doesNotMatch(html, /Residential Legal Notices/);
  assert.doesNotMatch(html, /Customer Approval Record|Homeowner approval record|Owner is responsible for utility locates/);
  assert.doesNotMatch(html, /Office-only|Internal packet assembly note|Private takeoff note|Private SOV backup/);
  assert.doesNotMatch(html, /files\.example\.test|Apex HQ Estimate Backup|Apex HQ GC Packet Lite/);
});

test("internal review estimate packet can include office-only backup sections when allowed", () => {
  const packet = deriveEstimatePrintPacket({
    estimate: {
      title: "Internal Review Estimate",
      scopeSummary: "Scope of Work:\nPlace concrete.",
      internalNotes: [
        "Visible office note.",
        "Local file URL should be tracked: file:///C:/secret/internal-margin.xlsx",
        "[Apex HQ GC Packet Lite]",
        JSON.stringify({
          proposalSummary: "GC proposal summary.",
          gcReviewNotes: "Office-only GC note.",
          internalPacketNotes: "Internal packet note.",
        }),
        "[/Apex HQ GC Packet Lite]",
        "[Apex HQ Estimate Backup]",
        JSON.stringify({
          sovRows: [{ section: "Mobilization", description: "Mobilize crew", quantity: "1", unit: "LS", amount: "$1,000" }],
          takeoffRows: [{ item: "Sidewalk", quantity: "500", unit: "SF", source: "A1.1", estimatorNote: "Field verify." }],
          referenceRows: [{ fileName: "Bluebeam slab screenshot.png", referenceType: "Screenshot", url: "https://files.example.test/slab.png", source: "A1.1", notes: "Plan takeoff reference." }],
          notes: "Backup note.",
        }),
        "[/Apex HQ Estimate Backup]",
      ].join("\n"),
      items: [],
    },
    packetSettings: {
      presetId: "internalReviewPacket",
      allowInternalSections: true,
      customization: {
        themeId: "custom-brand",
        customThemeName: "Office Review",
        headerColor: "#1f2937",
        headerTextColor: "#ffffff",
        accentColor: "#d97706",
        coverTitle: "Internal Bid Review",
        coverKicker: "Office Review Packet",
        tagline: "Estimator backup, scope checks, risks, and handoff notes for office use.",
        statementTitle: "Ready for office review.",
        statementBody: "Scope, pricing summary, SOV backup, takeoff references, internal notes, and review risks are organized for the office team before customer release.",
        reviewNote: "Office-only packet. Do not send to customers or field crews.",
      },
    },
  });
  const html = buildPrintDocumentHtml(packet);

  assert.equal(packet.packetMode, "internal");
  assert.match(html, /Office Review Packet/);
  assert.match(html, /Internal Bid Review/);
  assert.match(html, /Ready for office review\./);
  assert.match(html, /Do not send to customers or field crews/);
  assert.match(html, /--packet-header: #1f2937/);
  assert.match(html, /--packet-accent: #d97706/);
  assert.match(html, /Schedule of Values Backup/);
  assert.match(html, /Mobilization/);
  assert.match(html, /Takeoff Backup/);
  assert.match(html, /Sidewalk/);
  assert.match(html, /Reference Attachments/);
  assert.match(html, /Bluebeam slab screenshot/);
  assert.match(html, /Reference link tracked in Apex HQ/);
  assert.doesNotMatch(html, /files\.example\.test\/slab/);
  assert.match(html, /Internal Review Notes/);
  assert.match(html, /Visible office note/);
  assert.match(html, /Office-only GC note/);
  assert.match(html, /Internal packet note/);
  assert.match(html, /Backup note/);
});

test("internal review estimate packet uses polished office-review defaults", () => {
  const packet = deriveEstimatePrintPacket({
    estimate: {
      title: "Internal Review Estimate",
      createdAt: "2026-05-27T12:00:00.000Z",
      scopeSummary: "Scope of Work:\nPlace concrete.\n\nExclusions:\nTesting by others.",
      internalNotes: [
        "Visible office note.",
        "Local file URL should be tracked: file:///C:/secret/internal-margin.xlsx",
        "[Apex HQ GC Packet Lite]",
        JSON.stringify({
          proposalSummary: "GC proposal summary.",
          gcReviewNotes: "Office-only GC note.",
          internalPacketNotes: "Internal packet note.",
        }),
        "[/Apex HQ GC Packet Lite]",
        "[Apex HQ Estimate Backup]",
        JSON.stringify({
          sovRows: [{ section: "Mobilization", description: "Mobilize crew", quantity: "1", unit: "LS", amount: "$1,000" }],
          takeoffRows: [{ item: "Sidewalk", quantity: "500", unit: "SF", source: "A1.1", estimatorNote: "Field verify." }],
          referenceRows: [{ fileName: "Bluebeam slab screenshot.png", referenceType: "Screenshot", url: "https://files.example.test/slab.png", source: "A1.1", notes: "Plan takeoff reference." }],
          notes: "Backup note.",
        }),
        "[/Apex HQ Estimate Backup]",
        "[Apex HQ Sent Proposal History]",
        JSON.stringify([{ snapshotId: "snap-private", notes: "Private sent history" }]),
        "[/Apex HQ Sent Proposal History]",
      ].join("\n"),
      items: [{ description: "Base slab", quantity: 1, unit: "LS", unitPrice: 10000 }],
    },
    packetSettings: {
      presetId: "internalReviewPacket",
      allowInternalSections: true,
    },
  });
  const html = buildPrintDocumentHtml(packet);

  assert.equal(packet.packetMode, "internal");
  assert.match(html, /Office Review Packet/);
  assert.match(html, /Internal Bid Review/);
  assert.match(html, /Internal Review Packet/);
  assert.match(html, /Ready for office review\./);
  assert.match(html, /Why This Review Is Ready/);
  assert.match(html, /Review Summary/);
  assert.match(html, /Review focus/);
  assert.match(html, /SOV backup, takeoff references, internal notes, and review risks are organized/);
  assert.match(html, /Do not send to customers or field crews/);
  assert.match(html, /SOV backup/);
  assert.match(html, /Takeoff evidence/);
  assert.match(html, /Risk review/);
  assert.match(html, /Office-only/);
  assert.match(html, /Schedule of Values Backup/);
  assert.match(html, /Reference Attachments/);
  assert.match(html, /Bluebeam slab screenshot/);
  assert.match(html, /Reference link tracked in Apex HQ/);
  assert.match(html, /Internal Review Notes/);
  assert.match(html, /Visible office note/);
  assert.match(html, /Local file URL should be tracked: Link tracked in Apex HQ/);
  assert.match(html, /Office-only GC note/);
  assert.match(html, /Internal packet note/);
  assert.match(html, /Backup note/);
  assert.match(html, /Field verify/);
  assert.match(html, /Plan takeoff reference/);
  assert.doesNotMatch(html, /A contractor proposal packet/i);
  assert.doesNotMatch(html, /files\.example\.test\/slab/);
  assert.doesNotMatch(html, /file:\/\/\/C:\/secret/);
  assert.doesNotMatch(html, /Apex HQ proposal packet\./);
  assert.doesNotMatch(html, /Private sent history|Apex HQ Sent Proposal History/);
});

test("print packet helpers tolerate missing linked arrays and render clean empty states", () => {
  const reportPacket = deriveDailyReportPrintPacket({ companyName: "Apex HQ Demo", report: null });
  const jobPacket = deriveJobPrintPacket({ companyName: "Apex HQ Demo", job: { id: "J-1", title: "Empty Job", status: "draft" } });

  assert.match(buildPrintDocumentHtml(reportPacket), /No report selected/);
  assert.match(buildPrintDocumentHtml(jobPacket), /Nothing recorded\./);
});
